sLogo: parser.tests.BooleanTester Class Reference
parser.tests.BooleanTester Class Reference
Public Member Functions
void setUp () throws Exception
void testAnd () throws InvalidSemanticsException, InvalidArgumentsException
void testEqual () throws InvalidSemanticsException, InvalidArgumentsException
void testGreaterThan () throws InvalidSemanticsException, InvalidArgumentsException
void testLessThan () throws InvalidSemanticsException, InvalidArgumentsException
void testNot () throws InvalidSemanticsException, InvalidArgumentsException
void testNotEqual () throws InvalidSemanticsException, InvalidArgumentsException
void testOr () throws InvalidSemanticsException, InvalidArgumentsException
Package Attributes
Parser myParser
Random myRandom
Detailed Description
Definition at line 11 of file BooleanTester.java.
Member Function Documentation
void parser.tests.BooleanTester.setUp () throws Exception
Definition at line 17 of file BooleanTester.java.
void parser.tests.BooleanTester.testAnd () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 23 of file BooleanTester.java.
References parser.Parser.parseCommand().
void parser.tests.BooleanTester.testEqual () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 36 of file BooleanTester.java.
References parser.Parser.parseCommand().
void parser.tests.BooleanTester.testGreaterThan () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 52 of file BooleanTester.java.
References parser.Parser.parseCommand().
void parser.tests.BooleanTester.testLessThan () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 69 of file BooleanTester.java.
References parser.Parser.parseCommand().
void parser.tests.BooleanTester.testNot () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 86 of file BooleanTester.java.
References parser.Parser.parseCommand().
void parser.tests.BooleanTester.testNotEqual () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 100 of file BooleanTester.java.
References parser.Parser.parseCommand().
void parser.tests.BooleanTester.testOr () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 117 of file BooleanTester.java.
References parser.Parser.parseCommand().
Member Data Documentation
Parser parser.tests.BooleanTester.myParser package
Definition at line 13 of file BooleanTester.java.
Random parser.tests.BooleanTester.myRandom package
Definition at line 14 of file BooleanTester.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/tests/BooleanTester.java