sLogo: parser.tests.MathTester Class Reference
parser.tests.MathTester Class Reference
Public Member Functions
void setUp () throws Exception
void testSum () throws InvalidSemanticsException, InvalidArgumentsException
void testDifference () throws InvalidSemanticsException, InvalidArgumentsException
void testProduct () throws InvalidSemanticsException, InvalidArgumentsException
void testQuotient () throws InvalidSemanticsException, InvalidArgumentsException
void testMinus () throws InvalidSemanticsException, InvalidArgumentsException
void testRemainder () throws InvalidSemanticsException, InvalidArgumentsException
void testRandom () throws InvalidSemanticsException, InvalidArgumentsException
Private Attributes
Parser myParser
Random myRandom
Detailed Description
Definition at line 11 of file MathTester.java.
Member Function Documentation
void parser.tests.MathTester.setUp () throws Exception
Definition at line 17 of file MathTester.java.
void parser.tests.MathTester.testDifference () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 37 of file MathTester.java.
References parser.Parser.parseCommand().
void parser.tests.MathTester.testMinus () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 79 of file MathTester.java.
References parser.Parser.parseCommand().
void parser.tests.MathTester.testProduct () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 51 of file MathTester.java.
References parser.Parser.parseCommand().
void parser.tests.MathTester.testQuotient () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 65 of file MathTester.java.
References parser.Parser.parseCommand().
void parser.tests.MathTester.testRandom () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 106 of file MathTester.java.
References parser.Parser.parseCommand().
void parser.tests.MathTester.testRemainder () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 92 of file MathTester.java.
References parser.Parser.parseCommand().
void parser.tests.MathTester.testSum () throws InvalidSemanticsException, InvalidArgumentsException
Definition at line 23 of file MathTester.java.
References parser.Parser.parseCommand().
Member Data Documentation
Parser parser.tests.MathTester.myParser private
Definition at line 13 of file MathTester.java.
Random parser.tests.MathTester.myRandom private
Definition at line 14 of file MathTester.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/tests/MathTester.java