sLogo: view.windows.InformationView Class Reference
view.windows.InformationView Class Reference
Public Member Functions
InformationView ()
void update (Observable object, Object arg)
Private Member Functions
void setLabels ()
Private Attributes
List< LogoLabel > myLabelList
Static Private Attributes
static final String TITLE = "Turtle Information"
static final String[] LABEL_DESCRIPTIONS
static final ILabelInformation[] TURTLE_QUERIES
Detailed Description
Displays one turtle's basic information on a stylized panel
Author
Henrique Moraes
Definition at line 34 of file InformationView.java.
Constructor & Destructor Documentation
view.windows.InformationView.InformationView ()
Constructos for this class
Definition at line 50 of file InformationView.java.
References view.Window.TABBED_INFO_WINDOW_DIMENSION.
Member Function Documentation
void view.windows.InformationView.setLabels () private
Sets the special labels inside this panel
Definition at line 64 of file InformationView.java.
References view.labels.TitleLabel.getGridBagConstraints(), and view.labels.InformationLabel.getGridBagConstraints().
void view.windows.InformationView.update (Observable object, Object arg)
Updates the labels' information
Definition at line 81 of file InformationView.java.
References model.TurtleManager.getTurtles(), and view.labels.LogoLabel.setText().
Member Data Documentation
final String [] view.windows.InformationView.LABEL_DESCRIPTIONS static private
Initial value:
=
    { "Absolute Heading: ", "X Position: ", "Y Position: ",
     "Pen Down? ", "Is Hiding? " }
Definition at line 37 of file InformationView.java.
List<LogoLabel> view.windows.InformationView.myLabelList private
Definition at line 45 of file InformationView.java.
final String view.windows.InformationView.TITLE = "Turtle Information" static private
Definition at line 35 of file InformationView.java.
final ILabelInformation [] view.windows.InformationView.TURTLE_QUERIES static private
Initial value:
= { new Heading(null),
                                                               new XCor(null), new YCor(null),
                                                               new IsPenDown(null),
                                                               new IsShowing(null) }
Definition at line 40 of file InformationView.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/view/windows/InformationView.java