sLogo: view.windows.VariablesWindow Class Reference
view.windows.VariablesWindow Class Reference
Public Member Functions
VariablesWindow ()
void update ()
void update (Observable work, Object arg1)
Static Public Attributes
static final String[] COLUMN_NAMES
static final Dimension TABLE_DIMENSION
static final int VALUE_INDEX = 2
static final int NAME_INDEX = 0
static final int SCOPE_INDEX = 1
static final int COL_NUM = 3
Private Member Functions
JScrollPane createTablePanel ()
void setTableListener ()
JPanel createButtonsPanel ()
JButton createOkButton ()
ActionListener createRemoveListener ()
ActionListener createNewListener ()
Private Attributes
LogoTable myTable
DefaultTableModel myModel
IError myErrorNotifier
VariableManager myVariableManager
boolean isCellAdding = false
JPanel myButtonsPanel
JPanel myCardsPanel
ResourceBundle myResource
Static Private Attributes
static final String[] EMPTY_ROW = new String[] { "", "", "" }
static final String NEW_BUTTON = Controller.RESOURCE.getString("New")
static final String OK_BUTTON = Controller.RESOURCE.getString("Ok")
Detailed Description
Definition at line 31 of file VariablesWindow.java.
Constructor & Destructor Documentation
view.windows.VariablesWindow.VariablesWindow ()
Constructor for variables window, creates table that holds variables
Definition at line 59 of file VariablesWindow.java.
References controller.Controller.RESOURCE, and view.Window.TABBED_INFO_WINDOW_DIMENSION.
Member Function Documentation
JPanel view.windows.VariablesWindow.createButtonsPanel () private
Returns
Panel containing buttons to manage variables table
Definition at line 111 of file VariablesWindow.java.
ActionListener view.windows.VariablesWindow.createNewListener () private
Returns
Appropriate listener for New button
Definition at line 195 of file VariablesWindow.java.
References view.components.LogoTable.getComboBox(), parser.VariableManager.getScopeNames(), and view.components.LogoTable.setLastRowEditable().
JButton view.windows.VariablesWindow.createOkButton () private
Returns
ok Button with appropriate listener
Restores the state of the panel to before adding a variable
Definition at line 132 of file VariablesWindow.java.
References parser.VariableManager.addToScope(), view.components.LogoTable.getComboBox(), controller.Controller.RESOURCE_ERROR, view.components.LogoTable.setLastRowEditable(), and controller.support.IError.showError().
ActionListener view.windows.VariablesWindow.createRemoveListener () private
Returns
Appropriate listener for remove button
Definition at line 177 of file VariablesWindow.java.
References parser.VariableManager.removeVariable().
JScrollPane view.windows.VariablesWindow.createTablePanel () private
Returns
scrollabe panel responsible for holding the variables table
Definition at line 70 of file VariablesWindow.java.
References view.Window.INFO_BACKGROUND_COLOR.
void view.windows.VariablesWindow.setTableListener () private
Sets the change listener for this table
Definition at line 88 of file VariablesWindow.java.
References controller.Controller.RESOURCE_ERROR, parser.VariableManager.setVariable(), and controller.support.IError.showError().
void view.windows.VariablesWindow.update ()
Updates the table information according to the variables in the workspace
Definition at line 215 of file VariablesWindow.java.
void view.windows.VariablesWindow.update (Observable work, Object arg1)
Updates the variables on this table
Definition at line 223 of file VariablesWindow.java.
References parser.VariableManager.getScopes(), and controller.Workspace.getVariables().
Member Data Documentation
final int view.windows.VariablesWindow.COL_NUM = 3 static
Definition at line 43 of file VariablesWindow.java.
final String [] view.windows.VariablesWindow.COLUMN_NAMES static
Initial value:
=
            new String[] { Controller.RESOURCE.getString("Name"),
                          Controller.RESOURCE.getString("Scope"),
                          Controller.RESOURCE.getString("Value") }
Definition at line 32 of file VariablesWindow.java.
final String [] view.windows.VariablesWindow.EMPTY_ROW = new String[] { "", "", "" } static private
Definition at line 36 of file VariablesWindow.java.
boolean view.windows.VariablesWindow.isCellAdding = false private
Definition at line 51 of file VariablesWindow.java.
JPanel view.windows.VariablesWindow.myButtonsPanel private
Definition at line 52 of file VariablesWindow.java.
JPanel view.windows.VariablesWindow.myCardsPanel private
Definition at line 53 of file VariablesWindow.java.
IError view.windows.VariablesWindow.myErrorNotifier private
Definition at line 49 of file VariablesWindow.java.
DefaultTableModel view.windows.VariablesWindow.myModel private
Definition at line 48 of file VariablesWindow.java.
ResourceBundle view.windows.VariablesWindow.myResource private
Definition at line 54 of file VariablesWindow.java.
LogoTable view.windows.VariablesWindow.myTable private
Definition at line 47 of file VariablesWindow.java.
VariableManager view.windows.VariablesWindow.myVariableManager private
Definition at line 50 of file VariablesWindow.java.
final int view.windows.VariablesWindow.NAME_INDEX = 0 static
Definition at line 41 of file VariablesWindow.java.
final String view.windows.VariablesWindow.NEW_BUTTON = Controller.RESOURCE.getString("New") static private
Definition at line 44 of file VariablesWindow.java.
final String view.windows.VariablesWindow.OK_BUTTON = Controller.RESOURCE.getString("Ok") static private
Definition at line 45 of file VariablesWindow.java.
final int view.windows.VariablesWindow.SCOPE_INDEX = 1 static
Definition at line 42 of file VariablesWindow.java.
Referenced by view.components.LogoTable.getCellEditor().
final Dimension view.windows.VariablesWindow.TABLE_DIMENSION static
Initial value:
=
            new Dimension(Window.TABBED_INFO_WINDOW_DIMENSION.width,
                          Window.TABBED_INFO_WINDOW_DIMENSION.height - 30)
Definition at line 37 of file VariablesWindow.java.
final int view.windows.VariablesWindow.VALUE_INDEX = 2 static
Definition at line 40 of file VariablesWindow.java.
Referenced by view.components.LogoTable.isCellEditable().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/view/windows/VariablesWindow.java