sLogo: parser.VariableScope Class Reference
parser.VariableScope Class Reference
Public Member Functions
VariableScope (String name)
boolean equals (Object o)
void setVariable (String variable, int value)
Integer getVariable (String var) throws InvalidArgumentsException
Integer removeVariable (String var)
Map< String, Integer > getVariables ()
boolean containsVariable (String name)
String getName ()
Private Attributes
String myName
Map< String, Integer > myVariables
Detailed Description
Represents a Variable Scope for use in the Variable Manager.
Author
Jonathan Schmidt
Definition at line 14 of file VariableScope.java.
Constructor & Destructor Documentation
parser.VariableScope.VariableScope (String name)
Creates a new instance of a Variable Scope
Parameters
name The name of the scope
Definition at line 24 of file VariableScope.java.
Referenced by parser.VariableScope.equals().
Member Function Documentation
boolean parser.VariableScope.containsVariable (String name)
Returns whether the scope contains a variable.
Parameters
name The name of the variable.
Returns
Whether it exists or not.
Definition at line 87 of file VariableScope.java.
Referenced by parser.VariableManager.setVariable().
boolean parser.VariableScope.equals (Object o)
Definition at line 30 of file VariableScope.java.
References parser.VariableScope.getName(), and parser.VariableScope.VariableScope().
String parser.VariableScope.getName ()
Returns
the name of the scope
Definition at line 94 of file VariableScope.java.
References parser.VariableScope.myName.
Referenced by parser.VariableManager.addToScope(), and parser.VariableScope.equals().
Integer parser.VariableScope.getVariable (String var) throws InvalidArgumentsException
Returns the value of the variable.
Parameters
var The name of the variable
Returns
The value of the variable
Exceptions
InvalidArgumentsException When the variable does not exist
Definition at line 56 of file VariableScope.java.
Map<String, Integer> parser.VariableScope.getVariables ()
Returns the map of variables for use externally.
Returns
The map of variables.
Definition at line 77 of file VariableScope.java.
References parser.VariableScope.myVariables.
Integer parser.VariableScope.removeVariable (String var)
Removes a variable from the scope.
Parameters
var The name of the variable to remove.
Returns
Definition at line 68 of file VariableScope.java.
void parser.VariableScope.setVariable (String variable, int value)
Set the specified variable to the value.
Parameters
variable The name of the variable.
value The value to set.
Definition at line 45 of file VariableScope.java.
Referenced by parser.VariableManager.addToScope(), and parser.VariableManager.setVariable().
Member Data Documentation
String parser.VariableScope.myName private
Definition at line 15 of file VariableScope.java.
Referenced by parser.VariableScope.getName().
Map<String, Integer> parser.VariableScope.myVariables private
Definition at line 17 of file VariableScope.java.
Referenced by parser.VariableScope.getVariables().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/VariableScope.java