sLogo: parser.VariableManager Class Reference
parser.VariableManager Class Reference
Public Member Functions
VariableManager ()
void setVariable (String variable, int value)
Integer getVariable (String var) throws InvalidArgumentsException
void removeVariable (String var)
Deque< VariableScope > getScopes ()
void createVariableScope (String vs)
void revertVariableScope ()
List< String > getScopeNames ()
void addToScope (String scope, String variable, int value)
Private Attributes
VariableScope myGlobal = new VariableScope("GLOBAL")
Deque< VariableScope > myScopes
Detailed Description
Author
Jonathan Schmidt
Definition at line 17 of file VariableManager.java.
Constructor & Destructor Documentation
parser.VariableManager.VariableManager ()
Creates a Variable Manager
Definition at line 26 of file VariableManager.java.
Member Function Documentation
void parser.VariableManager.addToScope (String scope, String variable, int value)
Adds a variable to a specific scope
Parameters
scope The scope to add the variable to.
variable The variable name to add.
value The value of the variable to set.
Definition at line 141 of file VariableManager.java.
References parser.VariableScope.getName(), controller.Controller.RESOURCE_ERROR, and parser.VariableScope.setVariable().
Referenced by view.windows.VariablesWindow.createOkButton().
void parser.VariableManager.createVariableScope (String vs)
Creates a new scope for the Variable Manager. Makes sure it has a unique value.
Parameters
vs The name of the variable scope
Definition at line 103 of file VariableManager.java.
Referenced by parser.commands.other.Repeat.evaluate(), parser.commands.other.DoTimes.evaluate(), parser.commands.other.For.evaluate(), and parser.nodes.CommandNode.evaluate().
List<String> parser.VariableManager.getScopeNames ()
Returns
list with name of scopes of this manager
Definition at line 126 of file VariableManager.java.
Referenced by view.windows.VariablesWindow.createNewListener().
Deque<VariableScope> parser.VariableManager.getScopes ()
Returns
Deque with variable scopes of this manager
Definition at line 93 of file VariableManager.java.
References parser.VariableManager.myScopes.
Referenced by view.windows.VariablesWindow.update().
Integer parser.VariableManager.getVariable (String var) throws InvalidArgumentsException
Returns the value of the variable specified. The variable is returned from the most local scope.
Parameters
var The variable name
Returns
Exceptions
InvalidArgumentsException
Definition at line 58 of file VariableManager.java.
void parser.VariableManager.removeVariable (String var)
Returns the value of the variable specified. The variable is returned from the most local scope.
Parameters
var The name of the variable
Definition at line 79 of file VariableManager.java.
References controller.Controller.RESOURCE_ERROR.
Referenced by view.windows.VariablesWindow.createRemoveListener().
void parser.VariableManager.revertVariableScope ()
Sets the scope to be the previous scope. This will be called at the end of custom function.
Parameters
prev
Definition at line 119 of file VariableManager.java.
Referenced by parser.commands.other.Repeat.evaluate(), parser.commands.other.DoTimes.evaluate(), parser.commands.other.For.evaluate(), and parser.nodes.CommandNode.evaluate().
void parser.VariableManager.setVariable (String variable, int value)
Sets the specified variable to be the specified value.
Parameters
variable
value
Definition at line 37 of file VariableManager.java.
References parser.VariableScope.containsVariable(), and parser.VariableScope.setVariable().
Referenced by parser.commands.other.Repeat.evaluate(), parser.commands.other.DoTimes.evaluate(), parser.commands.other.For.evaluate(), parser.nodes.CommandNode.evaluate(), and view.windows.VariablesWindow.setTableListener().
Member Data Documentation
VariableScope parser.VariableManager.myGlobal = new VariableScope("GLOBAL") private
Definition at line 19 of file VariableManager.java.
Deque<VariableScope> parser.VariableManager.myScopes private
Definition at line 21 of file VariableManager.java.
Referenced by parser.VariableManager.getScopes().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/VariableManager.java