sLogo: parser.commands.other.DoTimes Class Reference
parser.commands.other.DoTimes Class Reference
Public Member Functions
DoTimes (Deque< SyntaxNode > queue)
int evaluate (IParserProvider w) throws InvalidArgumentsException
Public Member Functions inherited from parser.nodes.BinaryNode
BinaryNode (SyntaxNode left, SyntaxNode right)
BinaryNode (Deque< SyntaxNode > queue)
SyntaxNode getLeft ()
SyntaxNode getRight ()
Public Member Functions inherited from parser.nodes.ParameterNode
int getParameterCount ()
Public Member Functions inherited from parser.nodes.SyntaxNode
abstract int evaluate (IParserProvider w) throws InvalidArgumentsException
Private Member Functions
void checkSyntax () throws InvalidArgumentsException
Static Private Attributes
static final String FIRST_ARGUMENT = "First argument in first list must be a variable."
static final String FIRST_LIST_CONTENT
static final String FIRST_LIST = "First argument must be a list."
static final String SECOND_LIST = "Second argument must be a list of commands to run."
Additional Inherited Members
Protected Member Functions inherited from parser.nodes.ParameterNode
void addParameter (int index, SyntaxNode node)
SyntaxNode getParameter (int index)
Detailed Description
Implements the Do Times control structure. Runs the specified command list a certain number of times. Assigns the current count of the loop to the specified variable name. *
Author
Jonathan Schmidt
Definition at line 21 of file DoTimes.java.
Constructor & Destructor Documentation
parser.commands.other.DoTimes.DoTimes (Deque< SyntaxNode > queue)
Creates Do Times Command Node
Parameters
queue The list of nodes that come before this command
Definition at line 35 of file DoTimes.java.
Member Function Documentation
void parser.commands.other.DoTimes.checkSyntax () throws InvalidArgumentsException private
Definition at line 59 of file DoTimes.java.
References parser.nodes.ListNode.getContents(), parser.nodes.BinaryNode.getLeft(), and parser.nodes.BinaryNode.getRight().
Referenced by parser.commands.other.DoTimes.evaluate().
int parser.commands.other.DoTimes.evaluate (IParserProvider w) throws InvalidArgumentsException
Definition at line 40 of file DoTimes.java.
References parser.commands.other.DoTimes.checkSyntax(), parser.VariableManager.createVariableScope(), parser.nodes.SyntaxNode.evaluate(), parser.nodes.BinaryNode.getLeft(), parser.nodes.BinaryNode.getRight(), parser.VariableManager.revertVariableScope(), and parser.VariableManager.setVariable().
Member Data Documentation
final String parser.commands.other.DoTimes.FIRST_ARGUMENT = "First argument in first list must be a variable." static private
Definition at line 23 of file DoTimes.java.
final String parser.commands.other.DoTimes.FIRST_LIST = "First argument must be a list." static private
Definition at line 27 of file DoTimes.java.
final String parser.commands.other.DoTimes.FIRST_LIST_CONTENT static private
Initial value:
=
            "The first list must contain both a " +
                    "variable and a number of times for the loop to run."
Definition at line 24 of file DoTimes.java.
final String parser.commands.other.DoTimes.SECOND_LIST = "Second argument must be a list of commands to run." static private
Definition at line 28 of file DoTimes.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/commands/other/DoTimes.java