sLogo: controller.Workspace Class Reference
controller.Workspace Class Reference
Public Member Functions
Workspace (String name)
Workspace ()
void update ()
Map< String, CustomCommand > getCommandMap ()
void execute (List< SyntaxNode > commands)
Turtle getTurtle ()
TurtleManager getTurtleManager ()
void paint (Graphics2D pen)
void updateInformation ()
Map< Integer, Turtle > getAllTurtles ()
void activateTurtle (int index)
void deactivateTurtle (int index)
String getName ()
VariableManager getVariables ()
void saveWorkspace (Writer w)
void showError (String message)
void addTurtle (int index)
void addCommand (CustomCommand com)
CustomCommand getCommand (String command)
void addHistory (String s)
void addExecutableHistory (List< SyntaxNode > command)
List< String > getHistory ()
int setBackground (int colorIndex)
void setHighlighted (boolean active)
void setImage (String path)
boolean getHighlighted ()
Canvas getCanvas ()
void addTurtleObserver (Observer o)
void setStroke (Stroke stroke)
void setStroke (Strokes type, float thickness)
ColorManager getColors ()
void setStrokeType (Strokes s)
void addTurtleImage (int index, String imageDir)
WSUndoManager getUndoManager ()
Static Public Attributes
static final String UNTITLED = "Untitled"
Private Attributes
Map< String, CustomCommand > myCommandMap
ResourceBundle myErrorResource
String myName
List< String > myHistory
VariableManager myVariables
ColorManager myPalette
Canvas myCanvas
TurtleManager myTurtleManager
WSUndoManager myUndoManager
Detailed Description
Contains command information (history) for the particular workspace, holds turtle, allows saving of workspace
Author
XuRui, Ziqiang Huang, Henrique Moraes
Definition at line 36 of file Workspace.java.
Constructor & Destructor Documentation
controller.Workspace.Workspace (String name)
Definition at line 49 of file Workspace.java.
controller.Workspace.Workspace ()
Workspace constructor
Definition at line 57 of file Workspace.java.
References controller.Controller.RESOURCE_ERROR, and controller.Workspace.UNTITLED.
Member Function Documentation
void controller.Workspace.activateTurtle (int index)
Activates the turtle specified by the index
Definition at line 140 of file Workspace.java.
References model.TurtleManager.activate(), and controller.Workspace.update().
Referenced by controller.Controller.createCheckBoxItemListener().
void controller.Workspace.addCommand (CustomCommand com)
Add a custom command to the current context.
Parameters
com The custom command to add
Implements parser.IParserProvider.
Definition at line 197 of file Workspace.java.
References parser.CustomCommand.getName().
void controller.Workspace.addExecutableHistory (List< SyntaxNode > command)
Add commands to UndoManager
Parameters
command
Definition at line 220 of file Workspace.java.
References controller.WSUndoManager.addEditToHistory().
Referenced by controller.Controller.processCommand().
void controller.Workspace.addHistory (String s)
Parameters
s command to be added to command history
Definition at line 211 of file Workspace.java.
Referenced by controller.Controller.createEditMenu(), controller.Controller.createPhysicalCommands(), controller.Controller.createVisualCommands(), and controller.Controller.processCommand().
void controller.Workspace.addTurtle (int index)
Adds a new turtle with the specified index to the workspace
Parameters
index
Definition at line 191 of file Workspace.java.
References model.TurtleManager.addNew(), and controller.Workspace.update().
Referenced by controller.Controller.createSettingMenu().
void controller.Workspace.addTurtleImage (int index, String imageDir)
Parameters
index of the image
imageDir Directory of the image
Definition at line 307 of file Workspace.java.
References model.TurtleManager.addTurtleImage().
void controller.Workspace.addTurtleObserver (Observer o)
Parameters
o observer to be added to the turtle manager
Definition at line 269 of file Workspace.java.
Referenced by view.Window.setObservers().
void controller.Workspace.deactivateTurtle (int index)
Activates the turtle specified by the index
Definition at line 148 of file Workspace.java.
References model.TurtleManager.deactivateTurtle(), and controller.Workspace.update().
Referenced by controller.Controller.createCheckBoxItemListener().
void controller.Workspace.execute (List< SyntaxNode > commands)
Execute command within workspace
Parameters
commands
Definition at line 89 of file Workspace.java.
References controller.Workspace.showError().
Referenced by controller.WSUndoManager.executeHistory(), controller.Controller.processCommand(), controller.Controller.processFile(), and controller.WSUndoManager.redo().
Map<Integer, Turtle> controller.Workspace.getAllTurtles ()
Returns
All the Turtles associated with this workspace
Definition at line 133 of file Workspace.java.
References model.TurtleManager.getAllTurtles().
Referenced by controller.Controller.createTellMenuListener().
Canvas controller.Workspace.getCanvas ()
Returns
Canvas associated with this workspace
Definition at line 262 of file Workspace.java.
References controller.Workspace.myCanvas.
Referenced by controller.Controller.createSettingMenu(), and view.Window.createWorkspace().
ColorManager controller.Workspace.getColors ()
Color Manager for this workspace
Implements parser.IParserProvider.
Definition at line 292 of file Workspace.java.
References controller.Workspace.myPalette.
Referenced by controller.Controller.createSettingMenu().
CustomCommand controller.Workspace.getCommand (String command)
Returns the Custom Command from the current context that has the name of the command specified.
Parameters
command The command name to look up
Returns
The custom command result.
Implements parser.IParserProvider.
Definition at line 203 of file Workspace.java.
Map<String, CustomCommand> controller.Workspace.getCommandMap ()
Returns
Map with commands for this workspace
Definition at line 80 of file Workspace.java.
References controller.Workspace.myCommandMap.
Referenced by view.windows.CustomCommandWindow.update().
boolean controller.Workspace.getHighlighted ()
Returns
true if highlighting active turtles is enabled
Definition at line 255 of file Workspace.java.
References model.TurtleManager.getHighlighted().
List<String> controller.Workspace.getHistory ()
Definition at line 224 of file Workspace.java.
References controller.Workspace.myHistory.
Referenced by view.windows.PreviousCommandWindow.update().
String controller.Workspace.getName ()
Returns
Name of this workspace
Definition at line 156 of file Workspace.java.
References controller.Workspace.myName.
Referenced by view.Window.createWorkspace().
Turtle controller.Workspace.getTurtle ()
Returns the current turtle of the context. This is being phased out to deal with multiple turtles.
Returns
The current turtle
Implements parser.IParserProvider.
Definition at line 104 of file Workspace.java.
References model.TurtleManager.getCurrent().
TurtleManager controller.Workspace.getTurtleManager ()
Returns the Turtle Manager of the context.
Returns
The Turtle Manager
Implements parser.IParserProvider.
Definition at line 109 of file Workspace.java.
References controller.Workspace.myTurtleManager.
Referenced by controller.Controller.createPhysicalCommands(), controller.Controller.createSettingMenu(), controller.Controller.createTellMenuListener(), controller.Controller.createVisualCommands(), controller.WSUndoManager.redo(), and controller.WSUndoManager.undo().
WSUndoManager controller.Workspace.getUndoManager ()
Definition at line 311 of file Workspace.java.
References controller.Workspace.myUndoManager.
Referenced by controller.Controller.createEditMenu().
VariableManager controller.Workspace.getVariables ()
Returns the Variable Manager of the context.
Returns
The Variable Manager
Implements parser.IParserProvider.
Definition at line 161 of file Workspace.java.
References controller.Workspace.myVariables.
Referenced by view.windows.VariablesWindow.update().
void controller.Workspace.paint (Graphics2D pen)
Painting method that gets called by the Canvas
Implements model.Paintable.
Definition at line 117 of file Workspace.java.
References model.TurtleManager.paint().
void controller.Workspace.saveWorkspace (Writer w)
save the variables and commands from the current workspace to a file
Definition at line 168 of file Workspace.java.
Referenced by controller.Controller.createFileCommands().
int controller.Workspace.setBackground (int colorIndex)
Sets the background of the current context to the color specified by the index.
Parameters
colorIndex The index of the color
Returns
Implements parser.IParserProvider.
Definition at line 230 of file Workspace.java.
References model.ColorManager.getColor(), and view.Canvas.setBackgroundColor().
void controller.Workspace.setHighlighted (boolean active)
Parameters
active whether currently active turtles should be highlighted or not
Definition at line 239 of file Workspace.java.
References model.TurtleManager.setHighlighted().
void controller.Workspace.setImage (String path)
Sets image according to a given image path
Parameters
path
Definition at line 248 of file Workspace.java.
References model.TurtleManager.setImage().
void controller.Workspace.setStroke (Stroke stroke)
Parameters
stroke stroke to be set on active turtles of this workspace
Definition at line 276 of file Workspace.java.
References model.TurtleManager.setStroke().
void controller.Workspace.setStroke (Strokes type, float thickness)
Parameters
type type of stroke to be set on active turtles of this workspace
thickness thickness of the stroke
Definition at line 284 of file Workspace.java.
References view.Canvas.createStroke(), and model.TurtleManager.setStroke().
void controller.Workspace.setStrokeType (Strokes s)
Parameters
s Stroke type to be set on active turtles' pens
Definition at line 299 of file Workspace.java.
References model.TurtleManager.setStrokeType().
void controller.Workspace.showError (String message)
Display any string message in a popup error dialog.
Implements controller.support.IError.
Definition at line 181 of file Workspace.java.
Referenced by controller.Controller.createEditMenu(), controller.Controller.createFileCommands(), controller.Controller.createHelpMenu(), controller.Controller.createSettingMenu(), controller.Workspace.execute(), controller.Controller.processCommand(), and controller.Controller.processFile().
void controller.Workspace.update ()
Updates the state of this workspace for the user
Definition at line 73 of file Workspace.java.
References model.TurtleManager.update().
Referenced by controller.Workspace.activateTurtle(), controller.Workspace.addTurtle(), controller.Controller.createPhysicalCommands(), controller.Controller.createVisualCommands(), controller.Workspace.deactivateTurtle(), and view.Window.updateObservers().
void controller.Workspace.updateInformation ()
Notifies objects that manage visual representation of variables, commands, and expression related to this workspace
Definition at line 125 of file Workspace.java.
Referenced by view.Window.updateObservers().
Member Data Documentation
Canvas controller.Workspace.myCanvas private
Definition at line 45 of file Workspace.java.
Referenced by controller.Workspace.getCanvas().
Map<String, CustomCommand> controller.Workspace.myCommandMap private
Definition at line 38 of file Workspace.java.
Referenced by controller.Workspace.getCommandMap().
ResourceBundle controller.Workspace.myErrorResource private
Definition at line 39 of file Workspace.java.
List<String> controller.Workspace.myHistory private
Definition at line 42 of file Workspace.java.
Referenced by controller.Workspace.getHistory().
String controller.Workspace.myName private
Definition at line 40 of file Workspace.java.
Referenced by controller.Workspace.getName().
ColorManager controller.Workspace.myPalette private
Definition at line 44 of file Workspace.java.
Referenced by controller.Workspace.getColors().
TurtleManager controller.Workspace.myTurtleManager private
Definition at line 46 of file Workspace.java.
Referenced by controller.Workspace.getTurtleManager().
WSUndoManager controller.Workspace.myUndoManager private
Definition at line 47 of file Workspace.java.
Referenced by controller.Workspace.getUndoManager().
VariableManager controller.Workspace.myVariables private
Definition at line 43 of file Workspace.java.
Referenced by controller.Workspace.getVariables().
final String controller.Workspace.UNTITLED = "Untitled" static
Definition at line 37 of file Workspace.java.
Referenced by controller.Workspace.Workspace().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/controller/Workspace.java