sLogo: view.Window Class Reference
view.Window Class Reference
Public Member Functions
Window (JTextField field, JMenuBar bar)
void createWorkspace ()
Canvas getCanvas ()
void makeListeners ()
void setTabListener ()
void setInfoTabListener ()
Workspace getWorkspace ()
Static Public Attributes
static final Color INFO_BACKGROUND_COLOR = new Color(GRAY_TONE, GRAY_TONE, GRAY_TONE)
static final Dimension TABBED_INFO_WINDOW_DIMENSION = new Dimension(220, 600)
static final Dimension WINDOW_DIMENSION = new Dimension(1030, 735)
Protected Member Functions
JButton createCommandButton ()
JButton createExpandTextButton ()
Private Member Functions
void setObservers (Workspace workspace)
void updateObservers ()
JComponent makeInformationView ()
JComponent createInputField ()
Private Attributes
int workspaceIndex = 1
ResourceBundle myResource
Canvas myCurrentCanvas
InformationView myInfoView
VariablesWindow myVariablesWindow
PreviousCommandWindow myPreCommandsWindow
CustomCommandWindow myCusCommandsWindow
JTabbedPane myTabbedPane
JTabbedPane myTabbedInfoWindow
JTextField myInputField
Static Private Attributes
static final int GRAY_TONE = 230
static final String WORKSPACE_NAME = "Workspace "
static final String INFO_TAB_NAME = "Information"
static final String VARIABLE_TAB_NAME = "Variables"
static final String PRECOMMAND_TAB_NAME = "Previous Commands"
static final String CUSCOMMAND_TAB_NAME = "Custom Commands"
Detailed Description
Window that holds all the user interface. Sends commands to controller in case user inputs anything
Author
Henrique Moraes, Ziqiang
Definition at line 36 of file Window.java.
Constructor & Destructor Documentation
view.Window.Window (JTextField field, JMenuBar bar)
Definition at line 59 of file Window.java.
References controller.Controller.RESOURCE, and view.components.ErrorBox.setWindow().
Member Function Documentation
JButton view.Window.createCommandButton () protected
Create a standard button to send the input in the text field to Controller
Definition at line 172 of file Window.java.
JButton view.Window.createExpandTextButton () protected
Create a standard button to increase the area of the text field
Definition at line 181 of file Window.java.
JComponent view.Window.createInputField () private
Establishes the south area of the Window in which the user writes inputs
Returns
JComponent with the structure for the input area
Definition at line 160 of file Window.java.
void view.Window.createWorkspace ()
Creates a new workspace and sets the associated canvas to it on the tabbed pane
Implements view.WorkspaceHandler.
Definition at line 117 of file Window.java.
References controller.Workspace.getCanvas(), and controller.Workspace.getName().
Canvas view.Window.getCanvas ()
Returns
Currently selected Canvas
Definition at line 139 of file Window.java.
Workspace view.Window.getWorkspace ()
Returns
currently active workspace
Implements view.WorkspaceHandler.
Definition at line 223 of file Window.java.
References view.Canvas.getPaintableResource().
JComponent view.Window.makeInformationView () private
Creates a scrollable informationView
Returns
Information View of this program
Definition at line 148 of file Window.java.
void view.Window.makeListeners ()
creates listeners for this window
Definition at line 189 of file Window.java.
void view.Window.setInfoTabListener ()
Set the Listener to update the information panel whenever tabs are changed
Definition at line 213 of file Window.java.
void view.Window.setObservers (Workspace workspace) private
Sets the necessary observers for the turtle of this Workspace
Parameters
turtle Observed turtle
Definition at line 103 of file Window.java.
References controller.Workspace.addTurtleObserver().
void view.Window.setTabListener ()
Set the Listener to update the current canvas whenever tabs are changed
Definition at line 198 of file Window.java.
void view.Window.updateObservers () private
Updates both the Canvas and InfoView about the changes on the turtle
Definition at line 130 of file Window.java.
References view.Canvas.getPaintableResource(), controller.Workspace.update(), and controller.Workspace.updateInformation().
Member Data Documentation
final String view.Window.CUSCOMMAND_TAB_NAME = "Custom Commands" static private
Definition at line 45 of file Window.java.
final int view.Window.GRAY_TONE = 230 static private
Definition at line 37 of file Window.java.
final Color view.Window.INFO_BACKGROUND_COLOR = new Color(GRAY_TONE, GRAY_TONE, GRAY_TONE) static
Definition at line 38 of file Window.java.
Referenced by view.windows.VariablesWindow.createTablePanel().
final String view.Window.INFO_TAB_NAME = "Information" static private
Definition at line 42 of file Window.java.
Canvas view.Window.myCurrentCanvas private
Definition at line 50 of file Window.java.
CustomCommandWindow view.Window.myCusCommandsWindow private
Definition at line 54 of file Window.java.
InformationView view.Window.myInfoView private
Definition at line 51 of file Window.java.
JTextField view.Window.myInputField private
Definition at line 57 of file Window.java.
PreviousCommandWindow view.Window.myPreCommandsWindow private
Definition at line 53 of file Window.java.
ResourceBundle view.Window.myResource private
Definition at line 48 of file Window.java.
JTabbedPane view.Window.myTabbedInfoWindow private
Definition at line 56 of file Window.java.
JTabbedPane view.Window.myTabbedPane private
Definition at line 55 of file Window.java.
VariablesWindow view.Window.myVariablesWindow private
Definition at line 52 of file Window.java.
final String view.Window.PRECOMMAND_TAB_NAME = "Previous Commands" static private
Definition at line 44 of file Window.java.
final Dimension view.Window.TABBED_INFO_WINDOW_DIMENSION = new Dimension(220, 600) static
Definition at line 40 of file Window.java.
Referenced by view.windows.InformationView.InformationView(), and view.windows.VariablesWindow.VariablesWindow().
final String view.Window.VARIABLE_TAB_NAME = "Variables" static private
Definition at line 43 of file Window.java.
final Dimension view.Window.WINDOW_DIMENSION = new Dimension(1030, 735) static
Definition at line 41 of file Window.java.
final String view.Window.WORKSPACE_NAME = "Workspace " static private
Definition at line 39 of file Window.java.
int view.Window.workspaceIndex = 1 private
Definition at line 47 of file Window.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/view/Window.java