sLogo: parser.nodes.TernaryNode Class Reference
parser.nodes.TernaryNode Class Reference abstract
Public Member Functions
TernaryNode (SyntaxNode left, SyntaxNode middle, SyntaxNode right)
TernaryNode (Deque< SyntaxNode > queue)
SyntaxNode getMiddle ()
Public Member Functions inherited from parser.nodes.BinaryNode
BinaryNode (SyntaxNode left, SyntaxNode right)
BinaryNode (Deque< SyntaxNode > queue)
SyntaxNode getLeft ()
SyntaxNode getRight ()
Public Member Functions inherited from parser.nodes.ParameterNode
int getParameterCount ()
Public Member Functions inherited from parser.nodes.SyntaxNode
abstract int evaluate (IParserProvider w) throws InvalidArgumentsException
Static Private Attributes
static final int MIDDLE_PARAM = 3
Additional Inherited Members
Protected Member Functions inherited from parser.nodes.ParameterNode
void addParameter (int index, SyntaxNode node)
SyntaxNode getParameter (int index)
Detailed Description
This is a super class for any command that has 3 parameters. Extends the Binary Node
Author
Jonathan Schmidt
Definition at line 13 of file TernaryNode.java.
Constructor & Destructor Documentation
parser.nodes.TernaryNode.TernaryNode (SyntaxNode left, SyntaxNode middle, SyntaxNode right)
Create the Ternary Node
Parameters
left Syntax Node
middle Syntax Node
right Syntax Node
Definition at line 24 of file TernaryNode.java.
References parser.nodes.ParameterNode.addParameter().
parser.nodes.TernaryNode.TernaryNode (Deque< SyntaxNode > queue)
Creates a Ternary Node from a stack of nodes
Parameters
queue The stack of parameters
Definition at line 34 of file TernaryNode.java.
Member Function Documentation
SyntaxNode parser.nodes.TernaryNode.getMiddle ()
Returns
The middle parameter
Definition at line 42 of file TernaryNode.java.
References parser.nodes.ParameterNode.getParameter().
Referenced by parser.commands.other.To.checkSyntax(), parser.commands.other.IfElse.evaluate(), and parser.commands.other.To.evaluate().
Member Data Documentation
final int parser.nodes.TernaryNode.MIDDLE_PARAM = 3 static private
Definition at line 15 of file TernaryNode.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/Nodes/TernaryNode.java