sLogo: util.Vector Class Reference
util.Vector Class Reference
Public Member Functions
Vector ()
Vector (double angle, double magnitude)
Vector (Point2D source, Point2D target)
Vector (Vector other)
void reset ()
double getMagnitude ()
double getRelativeMagnitude (Vector other)
void scale (double change)
void setMagnitude (double value)
double getDirection ()
double getAngleBetween (Vector other)
void turn (double change)
double getXChange ()
double getYChange ()
void sum (Vector other)
void difference (Vector other)
void negate ()
Vector average (Vector other)
boolean equals (Object vector)
String toString ()
Static Public Member Functions
static double distanceBetween (Point2D p1, Point2D p2)
static double distanceBetween (double dx, double dy)
static double angleBetween (Point2D p1, Point2D p2)
static double angleBetween (double dx, double dy)
static boolean fuzzyEquals (double a, double b)
Protected Member Functions
void setDirection (double value)
Private Attributes
double myAngle
double myMagnitude
Detailed Description
This class represents a mathematical vector as a direction and magnitude. Originally created by Duvall, modified for this program
Author
Henrique Moraes
Definition at line 13 of file Vector.java.
Constructor & Destructor Documentation
util.Vector.Vector ()
Create a zero vector, i.e., with no magnitude.
Definition at line 22 of file Vector.java.
Referenced by util.Vector.average(), util.Vector.difference(), and util.Vector.equals().
util.Vector.Vector (double angle, double magnitude)
Create a vector in the given direction with the given magnitude.
Definition at line 29 of file Vector.java.
References util.Vector.setDirection(), and util.Vector.setMagnitude().
util.Vector.Vector (Point2D source, Point2D target)
Create a vector whose direction and magnitude are determined by direction and distance between the two given points.
Definition at line 38 of file Vector.java.
References util.Vector.angleBetween(), util.Vector.distanceBetween(), util.Vector.setDirection(), and util.Vector.setMagnitude().
util.Vector.Vector (Vector other)
Create a vector that is identical to the given other vector.
Definition at line 48 of file Vector.java.
References util.Vector.getDirection(), and util.Vector.getMagnitude().
Member Function Documentation
static double util.Vector.angleBetween (Point2D p1, Point2D p2) static
Returns the angle between the given two points
Definition at line 229 of file Vector.java.
Referenced by util.Vector.sum(), and util.Vector.Vector().
static double util.Vector.angleBetween (double dx, double dy) static
Returns the angle represented by the given dx and dy
Definition at line 236 of file Vector.java.
Vector util.Vector.average (Vector other)
Returns the average of this vector with the given other vector.
Definition at line 183 of file Vector.java.
References util.Vector.getDirection(), util.Vector.getMagnitude(), and util.Vector.Vector().
void util.Vector.difference (Vector other)
Subtracts the given vector from this vector.
Definition at line 165 of file Vector.java.
References util.Vector.negate(), util.Vector.sum(), and util.Vector.Vector().
static double util.Vector.distanceBetween (Point2D p1, Point2D p2) static
Returns the distance between given two points
Definition at line 215 of file Vector.java.
Referenced by model.Turtle.setPosition(), util.Vector.sum(), util.Vector.Vector(), and model.Turtle.wrapOnBoundary().
static double util.Vector.distanceBetween (double dx, double dy) static
Returns the distance represented by the given dx and dy
Definition at line 222 of file Vector.java.
boolean util.Vector.equals (Object vector)
Return true if this vector has the same magnitude and direction as the given other vector.
Definition at line 193 of file Vector.java.
References util.Vector.fuzzyEquals(), util.Vector.getDirection(), util.Vector.getMagnitude(), and util.Vector.Vector().
static boolean util.Vector.fuzzyEquals (double a, double b) static
Returns true if two real values are approximately equal.
For more details, see http://www.ibm.com/developerworks/java/library/j-jtp0114/#N10255
This function exists in many add-on libraries, but not standard Java :(
Definition at line 249 of file Vector.java.
Referenced by util.Vector.equals().
double util.Vector.getAngleBetween (Vector other)
Returns the angle between this vector and the given other vector.
Definition at line 109 of file Vector.java.
References util.Vector.getDirection().
Referenced by model.Turtle.faceTowards(), util.Vector.getRelativeMagnitude(), and model.Turtle.setHeading().
double util.Vector.getDirection ()
Returns this vector's direction (in degrees).
Definition at line 99 of file Vector.java.
Referenced by util.Vector.average(), util.Vector.equals(), util.Vector.getAngleBetween(), model.Turtle.getComplementPoint(), model.Turtle.getHeading(), util.Vector.getXChange(), util.Vector.getYChange(), model.Turtle.setPosition(), util.Vector.toString(), model.Turtle.transform(), util.Vector.turn(), and util.Vector.Vector().
double util.Vector.getMagnitude ()
Returns this vector's magnitude (in pixels).
Definition at line 63 of file Vector.java.
References util.Vector.myMagnitude.
Referenced by util.Vector.average(), util.Vector.equals(), model.Turtle.getComplementPoint(), util.Vector.getRelativeMagnitude(), util.Vector.getXChange(), util.Vector.getYChange(), model.Turtle.move(), util.Vector.scale(), util.Vector.toString(), and util.Vector.Vector().
double util.Vector.getRelativeMagnitude (Vector other)
Returns this vector's magnitude relative to the given other vector.
More formally, returns the magnitude of this vector projected onto the given other vector.
Definition at line 73 of file Vector.java.
References util.Vector.getAngleBetween(), and util.Vector.getMagnitude().
double util.Vector.getXChange ()
Returns the change in only the X direction represented by this vector.
Definition at line 130 of file Vector.java.
References util.Vector.getDirection(), and util.Vector.getMagnitude().
Referenced by util.Vector.sum(), and util.Location.translate().
double util.Vector.getYChange ()
Returns the change in only the Y direction represented by this vector.
Definition at line 137 of file Vector.java.
References util.Vector.getDirection(), and util.Vector.getMagnitude().
Referenced by util.Vector.sum(), and util.Location.translate().
void util.Vector.negate ()
Returns a vector of the same magnitude, but in the opposite direction as this vector.
Definition at line 176 of file Vector.java.
References util.Vector.turn().
Referenced by util.Vector.difference().
void util.Vector.reset ()
Reset this vector to zero.
Definition at line 55 of file Vector.java.
References util.Vector.setDirection(), and util.Vector.setMagnitude().
void util.Vector.scale (double change)
Scales this vector's magnitude by the given change value.
A value of 1 leaves the magnitude unchanged
Values less than 1 reduce the magnitude
Values greater than 1 increase the magnitude
Definition at line 85 of file Vector.java.
References util.Vector.getMagnitude(), and util.Vector.setMagnitude().
void util.Vector.setDirection (double value) protected
Sets this vector's direction to the given value.
Definition at line 123 of file Vector.java.
Referenced by util.Vector.reset(), util.Vector.sum(), util.Vector.turn(), and util.Vector.Vector().
void util.Vector.setMagnitude (double value)
Sets this vector's magnitude to the given value.
Definition at line 92 of file Vector.java.
Referenced by model.Turtle.move(), util.Vector.reset(), util.Vector.scale(), util.Vector.sum(), util.Vector.Vector(), and model.Turtle.wrapOnBoundary().
void util.Vector.sum (Vector other)
Adds the given vector to this vector.
Definition at line 144 of file Vector.java.
References util.Vector.angleBetween(), util.Vector.distanceBetween(), util.Vector.getXChange(), util.Vector.getYChange(), util.Vector.setDirection(), and util.Vector.setMagnitude().
Referenced by util.Vector.difference().
String util.Vector.toString ()
Returns this vector's values formatted as a string.
Definition at line 208 of file Vector.java.
References util.Vector.getDirection(), and util.Vector.getMagnitude().
void util.Vector.turn (double change)
Adjusts this vector's direction by the given change value.
Definition at line 116 of file Vector.java.
References util.Vector.getDirection(), and util.Vector.setDirection().
Referenced by model.Turtle.faceTowards(), util.Vector.negate(), model.Turtle.setHeading(), and model.Turtle.turn().
Member Data Documentation
double util.Vector.myAngle private
Definition at line 15 of file Vector.java.
double util.Vector.myMagnitude private
Definition at line 17 of file Vector.java.
Referenced by util.Vector.getMagnitude().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/util/Vector.java