sLogo: controller.WSUndoManager Class Reference
controller.WSUndoManager Class Reference
Public Member Functions
WSUndoManager (Workspace workspace)
void addEditToHistory (List< SyntaxNode > command)
void undo ()
void executeHistory ()
void redo ()
Private Member Functions
List< SyntaxNode > getLastUndoneCommand ()
List< SyntaxNode > getLastCommand ()
Private Attributes
Stack< List< SyntaxNode > > undoneCommands
Stack< List< SyntaxNode > > myActiveCommands
Workspace myWorkspace
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Manages undo and redo commands within workspace. Note that undo function may apply to multiple turtles.
Author
XuRui
Definition at line 18 of file WSUndoManager.java.
Constructor & Destructor Documentation
controller.WSUndoManager.WSUndoManager (Workspace workspace)
Definition at line 24 of file WSUndoManager.java.
Member Function Documentation
void controller.WSUndoManager.addEditToHistory (List< SyntaxNode > command)
Called by workspace to add commands to myActiveCommands
Parameters
command
Definition at line 54 of file WSUndoManager.java.
Referenced by controller.Workspace.addExecutableHistory().
void controller.WSUndoManager.executeHistory ()
Definition at line 71 of file WSUndoManager.java.
References controller.Workspace.execute().
Referenced by controller.WSUndoManager.undo().
List<SyntaxNode> controller.WSUndoManager.getLastCommand () private
Returns last command in active commands list
Returns
Definition at line 45 of file WSUndoManager.java.
Referenced by controller.WSUndoManager.undo().
List<SyntaxNode> controller.WSUndoManager.getLastUndoneCommand () private
Returns last undone command to be redone in workspace.
Returns
Definition at line 36 of file WSUndoManager.java.
Referenced by controller.WSUndoManager.redo().
void controller.WSUndoManager.redo ()
Redo the last undone command
Definition at line 81 of file WSUndoManager.java.
References controller.Workspace.execute(), controller.WSUndoManager.getLastUndoneCommand(), controller.Workspace.getTurtleManager(), and model.TurtleManager.update().
Referenced by controller.Controller.createEditMenu().
void controller.WSUndoManager.undo ()
Undo the latest command on every single applicable turtle
Definition at line 62 of file WSUndoManager.java.
References controller.WSUndoManager.executeHistory(), controller.WSUndoManager.getLastCommand(), controller.Workspace.getTurtleManager(), model.TurtleManager.getTurtles(), and model.TurtleManager.update().
Referenced by controller.Controller.createEditMenu().
Member Data Documentation
Stack<List<SyntaxNode> > controller.WSUndoManager.myActiveCommands private
Definition at line 21 of file WSUndoManager.java.
Workspace controller.WSUndoManager.myWorkspace private
Definition at line 22 of file WSUndoManager.java.
final long controller.WSUndoManager.serialVersionUID = 1L static private
Definition at line 19 of file WSUndoManager.java.
Stack<List<SyntaxNode> > controller.WSUndoManager.undoneCommands private
Definition at line 20 of file WSUndoManager.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/controller/WSUndoManager.java