sLogo: model.Turtle Class Reference
model.Turtle Class Reference
Public Member Functions
Turtle ()
int move (int pixels)
boolean wrapOnBoundary (Location initialPosition, int pixels)
Location getComplementPoint (Location loc, Vector heading)
boolean boundsExceeded ()
int turn (int degrees)
Rectangle getBounds ()
int setHeading (int degrees)
int faceTowards (int x, int y)
int setPosition (int x, int y)
int goHome ()
void paint (Graphics2D pen)
void paintTurtle (Graphics2D pen, Location point, AffineTransformOp op)
AffineTransformOp transform ()
Location getCenter ()
int getHeading ()
void setPenWriting (boolean write)
boolean isPenWriting ()
void setHiding (boolean hide)
void setHiding (int hide)
boolean isHiding ()
void setColor (Color color)
int clear ()
int getWidth ()
int getHeight ()
void setImage (BufferedImage myImage2)
BufferedImage getShape ()
void setStroke (Stroke stroke)
void setPenSize (int pixels)
Color getPenColor ()
void stamp ()
void clearStamp ()
void setStrokeType (Strokes s)
Static Public Attributes
static final String IMAGE_PATH = "/images/turtleSideways.png"
Package Functions
Location getPaintingPoint ()
Private Member Functions
void paintStamp (Graphics2D pen)
int viewerDegreeConversion (int degrees)
Private Attributes
Location myCenter
Vector myHeading
Pen myPen
BufferedImage myImage
int myWidth
int myHeight
boolean amHiding = false
List< Location > myStamp
Detailed Description
Creates a Turtle object that moves on the Canvas according to the user's input
Author
Henrique Moraes, Ziqiang Huang, Xu Rui
Definition at line 28 of file Turtle.java.
Constructor & Destructor Documentation
model.Turtle.Turtle ()
Definition at line 39 of file Turtle.java.
Member Function Documentation
boolean model.Turtle.boundsExceeded ()
Checks if turtle exceeds bounds.
Returns
Definition at line 132 of file Turtle.java.
References view.Canvas.DEFAULT_CANVAS_DIMENSION, util.Location.getIntX(), and util.Location.getIntY().
Referenced by model.Turtle.wrapOnBoundary().
int model.Turtle.clear ()
Erases turtle's trails and sends it to the home position
Returns
the distance turtle moved
Definition at line 315 of file Turtle.java.
References model.Turtle.goHome(), and model.Pen.myLines.
void model.Turtle.clearStamp ()
Definition at line 379 of file Turtle.java.
int model.Turtle.faceTowards (int x, int y)
Turns the turtle to face towards the specified location. Returns the number of degrees the turtle turned by.
Parameters
point
Returns
Definition at line 177 of file Turtle.java.
References util.Vector.getAngleBetween(), and util.Vector.turn().
Referenced by model.Turtle.setPosition().
Rectangle model.Turtle.getBounds ()
Returns
Rectangle containing the bounds of this object
Definition at line 151 of file Turtle.java.
References util.Location.getIntX(), util.Location.getIntY(), model.Turtle.getPaintingPoint(), model.Turtle.myHeight, and model.Turtle.myWidth.
Location model.Turtle.getCenter ()
Implements model.IState.
Definition at line 251 of file Turtle.java.
References util.Location.getVisualLocation().
Location model.Turtle.getComplementPoint (Location loc, Vector heading)
Definition at line 120 of file Turtle.java.
References util.Vector.getDirection(), and util.Vector.getMagnitude().
int model.Turtle.getHeading ()
Returns
the absolute heading of the object on the perspective of the user
Implements model.IState.
Definition at line 256 of file Turtle.java.
References util.Vector.getDirection(), and model.Turtle.viewerDegreeConversion().
int model.Turtle.getHeight ()
Definition at line 326 of file Turtle.java.
References model.Turtle.myHeight.
Referenced by model.TurtleManager.paint().
Location model.Turtle.getPaintingPoint () package
Returns
the location reference of the upper left corner of this image
Definition at line 213 of file Turtle.java.
References util.Location.translate().
Referenced by model.Turtle.getBounds(), model.TurtleManager.paint(), model.Turtle.paint(), and model.Turtle.stamp().
Color model.Turtle.getPenColor ()
Definition at line 371 of file Turtle.java.
References model.Pen.getPenColor().
BufferedImage model.Turtle.getShape ()
Definition at line 336 of file Turtle.java.
References model.Turtle.myImage.
int model.Turtle.getWidth ()
Definition at line 322 of file Turtle.java.
References model.Turtle.myWidth.
Referenced by model.TurtleManager.paint().
int model.Turtle.goHome ()
Moves the turtle to the center of the screen. Returns the number of pixels moved.
Definition at line 204 of file Turtle.java.
References model.Turtle.setHeading(), and model.Turtle.setPosition().
Referenced by model.Turtle.clear().
boolean model.Turtle.isHiding ()
Implements model.IState.
Definition at line 302 of file Turtle.java.
References model.Turtle.amHiding.
boolean model.Turtle.isPenWriting ()
Implements model.IState.
Definition at line 282 of file Turtle.java.
References model.Pen.isPenWriting().
int model.Turtle.move (int pixels)
Moves this turtle by the amount of pixels on the direction it is currently heading
Parameters
pixels pixels to move
Definition at line 52 of file Turtle.java.
References model.Pen.addLine(), util.Vector.getMagnitude(), util.Vector.setMagnitude(), util.Location.translate(), and model.Turtle.wrapOnBoundary().
void model.Turtle.paint (Graphics2D pen)
Implements model.Paintable.
Definition at line 220 of file Turtle.java.
References model.Turtle.getPaintingPoint(), model.Pen.paint(), model.Turtle.paintStamp(), model.Turtle.paintTurtle(), and model.Turtle.transform().
Referenced by model.TurtleManager.paint().
void model.Turtle.paintStamp (Graphics2D pen) private
Definition at line 234 of file Turtle.java.
References model.Turtle.paintTurtle(), and model.Turtle.transform().
Referenced by model.Turtle.paint().
void model.Turtle.paintTurtle (Graphics2D pen, Location point, AffineTransformOp op)
Definition at line 229 of file Turtle.java.
References util.Location.getIntX(), and util.Location.getIntY().
Referenced by model.Turtle.paint(), and model.Turtle.paintStamp().
void model.Turtle.setColor (Color color)
Definition at line 306 of file Turtle.java.
References model.Pen.setPenColor().
int model.Turtle.setHeading (int degrees)
Turns the turtle to the specified heading in degrees. Returns the number of degrees it turned by.
Parameters
degrees Absolute heading to turn to. this number is on the perspective of the user
Definition at line 163 of file Turtle.java.
References util.Vector.getAngleBetween(), util.Vector.turn(), and model.Turtle.viewerDegreeConversion().
Referenced by model.Turtle.goHome().
void model.Turtle.setHiding (boolean hide)
Definition at line 286 of file Turtle.java.
Referenced by model.Turtle.setHiding().
void model.Turtle.setHiding (int hide)
Definition at line 290 of file Turtle.java.
References model.Turtle.setHiding().
void model.Turtle.setImage (BufferedImage myImage2)
Definition at line 330 of file Turtle.java.
Referenced by model.TurtleManager.createTurtle().
void model.Turtle.setPenSize (int pixels)
Definition at line 344 of file Turtle.java.
References model.Pen.getStrokeType(), and model.Pen.setStroke().
void model.Turtle.setPenWriting (boolean write)
Checks for left and right bounds
Definition at line 277 of file Turtle.java.
References model.Pen.setPenWriting().
int model.Turtle.setPosition (int x, int y)
Moves the turtle to the a point on the screen. Returns the number of pixels moved.
Parameters
point
Returns
Definition at line 191 of file Turtle.java.
References util.Vector.distanceBetween(), model.Turtle.faceTowards(), util.Vector.getDirection(), and util.Location.translate().
Referenced by model.Turtle.goHome().
void model.Turtle.setStroke (Stroke stroke)
Definition at line 340 of file Turtle.java.
References model.Pen.setStroke().
Referenced by model.TurtleManager.addNew().
void model.Turtle.setStrokeType (Strokes s)
Definition at line 384 of file Turtle.java.
References model.Pen.setStrokeType().
void model.Turtle.stamp ()
Definition at line 375 of file Turtle.java.
References model.Turtle.getPaintingPoint().
AffineTransformOp model.Turtle.transform ()
Definition at line 242 of file Turtle.java.
References util.Vector.getDirection().
Referenced by model.Turtle.paint(), and model.Turtle.paintStamp().
int model.Turtle.turn (int degrees)
Turns the turtle by the number of degrees
Parameters
degrees degrees to turn
Definition at line 143 of file Turtle.java.
References util.Vector.turn().
int model.Turtle.viewerDegreeConversion (int degrees) private
Switches the values of the degrees because java works with a different perspective of the subject
Parameters
degrees degrees to invert perspective
Returns
degrees of Absolute Heading from the opposite perspective if the program uses its heading to display to the user, the degrees are converted to the user's perspective and vice-versa
Definition at line 269 of file Turtle.java.
Referenced by model.Turtle.getHeading(), and model.Turtle.setHeading().
boolean model.Turtle.wrapOnBoundary (Location initialPosition, int pixels)
Checks for top and bottom bounds
Definition at line 67 of file Turtle.java.
References model.Turtle.boundsExceeded(), view.Canvas.DEFAULT_CANVAS_DIMENSION, util.Vector.distanceBetween(), util.Location.getIntX(), util.Location.getIntY(), util.Location.getVisualLocation(), util.Vector.setMagnitude(), util.Location.setX(), and util.Location.setY().
Referenced by model.Turtle.move().
Member Data Documentation
boolean model.Turtle.amHiding = false private
Definition at line 36 of file Turtle.java.
Referenced by model.Turtle.isHiding().
final String model.Turtle.IMAGE_PATH = "/images/turtleSideways.png" static
Definition at line 32 of file Turtle.java.
Location model.Turtle.myCenter private
Definition at line 29 of file Turtle.java.
Vector model.Turtle.myHeading private
Definition at line 30 of file Turtle.java.
int model.Turtle.myHeight private
Definition at line 35 of file Turtle.java.
Referenced by model.Turtle.getBounds(), and model.Turtle.getHeight().
BufferedImage model.Turtle.myImage private
Definition at line 33 of file Turtle.java.
Referenced by model.Turtle.getShape().
Pen model.Turtle.myPen private
Definition at line 31 of file Turtle.java.
List<Location> model.Turtle.myStamp private
Definition at line 37 of file Turtle.java.
int model.Turtle.myWidth private
Definition at line 34 of file Turtle.java.
Referenced by model.Turtle.getBounds(), and model.Turtle.getWidth().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/model/Turtle.java