sLogo: util.Location Class Reference
util.Location Class Reference
Public Member Functions
Location ()
Location (double x, double y)
Location (Location source)
void reset ()
int getIntX ()
int getIntY ()
void translate (Vector amount)
void translate (double x, double y)
Location getVisualLocation ()
Vector difference (Point2D other)
void setX (double x)
void setY (double y)
Static Private Attributes
static final Dimension myCanvasDimension = Canvas.DEFAULT_CANVAS_DIMENSION
static final double X_OFFSET = Canvas.DEFAULT_CANVAS_DIMENSION.getWidth() / 2
static final double Y_OFFSET = Canvas.DEFAULT_CANVAS_DIMENSION.getHeight() / 2
Detailed Description
Represents a location on the canvas, supports visual location as well
Author
Henrique Moraes
Definition at line 15 of file Location.java.
Constructor & Destructor Documentation
util.Location.Location ()
Create a location at the origin.
Definition at line 23 of file Location.java.
util.Location.Location (double x, double y)
Create a location at given (x, y) coordinates.
Definition at line 30 of file Location.java.
util.Location.Location (Location source)
Create a location that is identical to the given other location.
Definition at line 37 of file Location.java.
Member Function Documentation
Vector util.Location.difference (Point2D other)
Returns a vector that is the difference between this location and the given other location.
Definition at line 95 of file Location.java.
int util.Location.getIntX ()
Returns
Integer x coordinate
Definition at line 51 of file Location.java.
Referenced by model.Turtle.boundsExceeded(), parser.commands.turtle.queries.XCor.evaluate(), model.Turtle.getBounds(), model.TurtleManager.paint(), model.Turtle.paintTurtle(), and model.Turtle.wrapOnBoundary().
int util.Location.getIntY ()
Returns
Integer y coordinate
Definition at line 58 of file Location.java.
Referenced by model.Turtle.boundsExceeded(), parser.commands.turtle.queries.YCor.evaluate(), model.Turtle.getBounds(), model.TurtleManager.paint(), model.Turtle.paintTurtle(), and model.Turtle.wrapOnBoundary().
Location util.Location.getVisualLocation ()
Used to convert a point from the program's coordinates to the user's visual perspective
Returns
Location with coordinates manipulated to the user's point of view
Definition at line 86 of file Location.java.
Referenced by model.Turtle.getCenter(), and model.Turtle.wrapOnBoundary().
void util.Location.reset ()
Reset this location to origin.
Definition at line 44 of file Location.java.
void util.Location.setX (double x)
Parameters
x location to be set
Definition at line 102 of file Location.java.
Referenced by model.Turtle.wrapOnBoundary().
void util.Location.setY (double y)
Parameters
y location to be set
Definition at line 109 of file Location.java.
Referenced by model.Turtle.wrapOnBoundary().
void util.Location.translate (Vector amount)
Move this location by given vector.
See also
java.awt.Point::translate(int, int)
Definition at line 67 of file Location.java.
References util.Vector.getXChange(), and util.Vector.getYChange().
Referenced by model.Turtle.getPaintingPoint(), model.Turtle.move(), and model.Turtle.setPosition().
void util.Location.translate (double x, double y)
Move this location by given coordinates.
Definition at line 74 of file Location.java.
Member Data Documentation
final Dimension util.Location.myCanvasDimension = Canvas.DEFAULT_CANVAS_DIMENSION static private
Definition at line 16 of file Location.java.
final double util.Location.X_OFFSET = Canvas.DEFAULT_CANVAS_DIMENSION.getWidth() / 2 static private
Definition at line 17 of file Location.java.
final double util.Location.Y_OFFSET = Canvas.DEFAULT_CANVAS_DIMENSION.getHeight() / 2 static private
Definition at line 18 of file Location.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/util/Location.java