sLogo: parser.commands.view.SetPalette Class Reference
parser.commands.view.SetPalette Class Reference
Public Member Functions
SetPalette (Deque< SyntaxNode > queue)
int evaluate (IParserProvider w) throws InvalidArgumentsException
Public Member Functions inherited from parser.nodes.ParameterNode
int getParameterCount ()
Public Member Functions inherited from parser.nodes.SyntaxNode
abstract int evaluate (IParserProvider w) throws InvalidArgumentsException
Static Private Attributes
static final int MAX_COLOR_VAL = 255
static final String RGB_VALUE_FORMAT = "RGB values must be a number between 0 and 255"
static final int BLUE = 2
static final int GREEN = 1
static final int RED = 0
static final int NUM_COLORS = 3
Additional Inherited Members
Protected Member Functions inherited from parser.nodes.ParameterNode
void addParameter (int index, SyntaxNode node)
SyntaxNode getParameter (int index)
Detailed Description
Implements the SetPalette function. Creates colors and adds them to the color manager
Author
Jonathan Schmidt
Definition at line 18 of file SetPalette.java.
Constructor & Destructor Documentation
parser.commands.view.SetPalette.SetPalette (Deque< SyntaxNode > queue)
Creates Random Command Node
Parameters
queue The list of nodes that come before this command
Definition at line 32 of file SetPalette.java.
References parser.nodes.ParameterNode.addParameter().
Member Function Documentation
int parser.commands.view.SetPalette.evaluate (IParserProvider w) throws InvalidArgumentsException
Definition at line 40 of file SetPalette.java.
References parser.commands.view.SetPalette.BLUE, parser.nodes.SyntaxNode.evaluate(), parser.nodes.ParameterNode.getParameter(), parser.commands.view.SetPalette.GREEN, parser.commands.view.SetPalette.NUM_COLORS, and parser.commands.view.SetPalette.RED.
Member Data Documentation
final int parser.commands.view.SetPalette.BLUE = 2 static private
Definition at line 22 of file SetPalette.java.
Referenced by parser.commands.view.SetPalette.evaluate().
final int parser.commands.view.SetPalette.GREEN = 1 static private
Definition at line 23 of file SetPalette.java.
Referenced by parser.commands.view.SetPalette.evaluate().
final int parser.commands.view.SetPalette.MAX_COLOR_VAL = 255 static private
Definition at line 20 of file SetPalette.java.
final int parser.commands.view.SetPalette.NUM_COLORS = 3 static private
Definition at line 25 of file SetPalette.java.
Referenced by parser.commands.view.SetPalette.evaluate().
final int parser.commands.view.SetPalette.RED = 0 static private
Definition at line 24 of file SetPalette.java.
Referenced by parser.commands.view.SetPalette.evaluate().
final String parser.commands.view.SetPalette.RGB_VALUE_FORMAT = "RGB values must be a number between 0 and 255" static private
Definition at line 21 of file SetPalette.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/commands/view/SetPalette.java