sLogo: view.Canvas Class Reference
view.Canvas Class Reference
Public Member Functions
Canvas (Paintable workspace)
void paintComponent (Graphics g)
void update (Observable object, Object arg)
Paintable getPaintableResource ()
void setGridSpacing (int space)
void setGrid (boolean enable)
boolean isGridEnabled ()
int getGridSpacing ()
void setBackgroundColor (Color c)
void setBackgroundImage (BufferedImage read)
Stroke createStroke (Strokes type, float thickness)
Static Public Attributes
static final Dimension DEFAULT_CANVAS_DIMENSION = new Dimension(830, 575)
static final Color DEFAULT_BACKGROUND = Color.white
static final Stroke GRID_STROKE
Private Member Functions
void drawGrid (Graphics2D pen)
Private Attributes
Paintable myPaintingResource
Color myBackgroundColor
Image myBackgroundImage
int myGridSpacing = 100
boolean gridEnabled = false
Static Private Attributes
static final Color DEFAULT_BACKGROUND_COLOR = Color.WHITE
static final int MARGIN_OFFSET = 13
static final int GRIDLINE_OFFSET = 3
Detailed Description
Canvas in which the interface gets painted. It displays the turtle and its respective lines
Author
Henrique Moraes, Ziqiang Huang
Definition at line 27 of file Canvas.java.
Constructor & Destructor Documentation
view.Canvas.Canvas (Paintable workspace)
Constructor for this class, automatically creates a workspace and a turtle
Definition at line 47 of file Canvas.java.
Member Function Documentation
Stroke view.Canvas.createStroke (Strokes type, float thickness)
Creates a stroke according to given parameters
Parameters
type type of stroke
thickness thickness of the stroke
Returns
A stroke based on the parameters given
Definition at line 174 of file Canvas.java.
Referenced by controller.Workspace.setStroke().
void view.Canvas.drawGrid (Graphics2D pen) private
Draws the grid of the Canvas. Notice: the two for loops are significantly similar, but the only solution I found was to break up into even more methods and use booleans
Parameters
pen Graphics used to paint the grid on this canvas
Definition at line 83 of file Canvas.java.
int view.Canvas.getGridSpacing ()
Returns
grid spacing of this Canvas
Definition at line 148 of file Canvas.java.
Paintable view.Canvas.getPaintableResource ()
Returns
the base informational components to paint on this canvas such as the workspace, as a Paintable
Definition at line 120 of file Canvas.java.
Referenced by view.Window.getWorkspace(), and view.Window.updateObservers().
boolean view.Canvas.isGridEnabled ()
Returns
visibility of the grid of this Canvas
Definition at line 141 of file Canvas.java.
void view.Canvas.paintComponent (Graphics g)
Paints the Canvas with its Turtle and lines
Definition at line 59 of file Canvas.java.
References model.Paintable.paint().
void view.Canvas.setBackgroundColor (Color c)
Parameters
c Background color to be set on this canvas
Definition at line 155 of file Canvas.java.
Referenced by controller.Workspace.setBackground().
void view.Canvas.setBackgroundImage (BufferedImage read)
Definition at line 162 of file Canvas.java.
Referenced by controller.Controller.createSettingMenu().
void view.Canvas.setGrid (boolean enable)
Parameters
space determines the spacing for the grid of this Canvas
Definition at line 134 of file Canvas.java.
void view.Canvas.setGridSpacing (int space)
Parameters
space determines the spacing for the grid of this Canvas
Definition at line 127 of file Canvas.java.
void view.Canvas.update (Observable object, Object arg)
Repaints all the components associated to this view
Definition at line 112 of file Canvas.java.
Member Data Documentation
final Color view.Canvas.DEFAULT_BACKGROUND = Color.white static
Definition at line 30 of file Canvas.java.
final Color view.Canvas.DEFAULT_BACKGROUND_COLOR = Color.WHITE static private
Definition at line 28 of file Canvas.java.
final Dimension view.Canvas.DEFAULT_CANVAS_DIMENSION = new Dimension(830, 575) static
Definition at line 29 of file Canvas.java.
Referenced by model.Turtle.boundsExceeded(), and model.Turtle.wrapOnBoundary().
final Stroke view.Canvas.GRID_STROKE static
Initial value:
=
            new BasicStroke(1, BasicStroke.CAP_SQUARE, BasicStroke.JOIN_ROUND, 1,
                            new float[] { 5 }, 0)
Definition at line 31 of file Canvas.java.
boolean view.Canvas.gridEnabled = false private
Definition at line 41 of file Canvas.java.
final int view.Canvas.GRIDLINE_OFFSET = 3 static private
Definition at line 35 of file Canvas.java.
final int view.Canvas.MARGIN_OFFSET = 13 static private
Definition at line 34 of file Canvas.java.
Color view.Canvas.myBackgroundColor private
Definition at line 38 of file Canvas.java.
Image view.Canvas.myBackgroundImage private
Definition at line 39 of file Canvas.java.
int view.Canvas.myGridSpacing = 100 private
Definition at line 40 of file Canvas.java.
Paintable view.Canvas.myPaintingResource private
Definition at line 37 of file Canvas.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/view/Canvas.java