sLogo: parser.Main Class Reference
parser.Main Class Reference
Static Public Member Functions
static void main (String[] args)
Static Private Member Functions
static void checkLine (Parser p) throws InvalidSemanticsException
static void checkFile (Parser p)
Static Private Attributes
static JFileChooser myChooser
Detailed Description
Definition at line 11 of file Main.java.
Member Function Documentation
static void parser.Main.checkFile (Parser p) static private
Definition at line 55 of file Main.java.
References parser.Parser.parseCommand().
Referenced by parser.Main.main().
static void parser.Main.checkLine (Parser p) throws InvalidSemanticsException static private
Definition at line 31 of file Main.java.
Referenced by parser.Main.main().
static void parser.Main.main (String[] args) static
Parameters
args text
Definition at line 18 of file Main.java.
References parser.Main.checkFile(), and parser.Main.checkLine().
Member Data Documentation
JFileChooser parser.Main.myChooser static private
Definition at line 13 of file Main.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/Main.java