sLogo: parser.reflection.ReflectionHelper Class Reference
parser.reflection.ReflectionHelper Class Reference
Static Public Member Functions
static SyntaxNode createInstanceOf (Class<?> c, Object...params) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, ClassDefinitionException
static Constructor<?> findConstructor (Class<?> c, Object...params) throws ClassDefinitionException
static Method findMethod (Class<?> c, String methodName, Class<?>[] params) throws NoSuchMethodException
static Method findMethod (Class<?> c, String methodName, Object[] params) throws NoSuchMethodException
Static Private Member Functions
static boolean paramsEqual (Class<?>[] c1, Class<?>[] c2)
static Class<?>[] toClassArray (Object...params)
Detailed Description
This is a class that makes it much easier to do reflection. It has a few methods that return the information that is needed.
Author
Jonathan Schmidt
Definition at line 17 of file ReflectionHelper.java.
Member Function Documentation
static SyntaxNode parser.reflection.ReflectionHelper.createInstanceOf (Class<?> c, Object... params) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, ClassDefinitionException static
Creates an instance of the specified class with the specified parameters.
Parameters
c The Class to create.
params The parameters to pass into the constructor
Returns
The SyntaxNode that has been created.
Exceptions
InstantiationException
IllegalAccessException
IllegalArgumentException
InvocationTargetException
ClassDefinitionException
Definition at line 32 of file ReflectionHelper.java.
References parser.reflection.ReflectionHelper.findConstructor().
Referenced by parser.SemanticsChecker.createNode(), and parser.nodes.ParamListNode.ParamListNode().
static Constructor<?> parser.reflection.ReflectionHelper.findConstructor (Class<?> c, Object... params) throws ClassDefinitionException static
Finds the Constructor of a specified class that take in the provided parameters.
Parameters
c The Class to search
params The parameters to find a constructor for
Returns
The constructor required to instantiate.
Exceptions
ClassDefinitionException
Definition at line 53 of file ReflectionHelper.java.
References parser.reflection.ReflectionHelper.paramsEqual(), and parser.reflection.ReflectionHelper.toClassArray().
Referenced by parser.reflection.ReflectionHelper.createInstanceOf().
static Method parser.reflection.ReflectionHelper.findMethod (Class<?> c, String methodName, Class<?>[] params) throws NoSuchMethodException static
Finds and returns the requested method.
Parameters
c The class to search in.
methodName The name of the Method.
params The parameters that the method takes in.
Returns
Exceptions
NoSuchMethodException
Definition at line 75 of file ReflectionHelper.java.
Referenced by model.TurtleManager.execute(), and parser.reflection.ReflectionHelper.findMethod().
static Method parser.reflection.ReflectionHelper.findMethod (Class<?> c, String methodName, Object[] params) throws NoSuchMethodException static
Finds and returns the requested method
Parameters
c The class to search in.
methodName The method name
params An array of objects that contain the parameters for the method.
Returns
The requested Method
Exceptions
NoSuchMethodException
Definition at line 90 of file ReflectionHelper.java.
References parser.reflection.ReflectionHelper.findMethod(), and parser.reflection.ReflectionHelper.toClassArray().
static boolean parser.reflection.ReflectionHelper.paramsEqual (Class<?>[] c1, Class<?>[] c2) static private
Definition at line 96 of file ReflectionHelper.java.
Referenced by parser.reflection.ReflectionHelper.findConstructor().
static Class<?> [] parser.reflection.ReflectionHelper.toClassArray (Object... params) static private
Definition at line 106 of file ReflectionHelper.java.
Referenced by parser.reflection.ReflectionHelper.findConstructor(), and parser.reflection.ReflectionHelper.findMethod().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/reflection/ReflectionHelper.java