sLogo: parser.nodes.SyntaxNode Class Reference
parser.nodes.SyntaxNode Class Reference abstract
Public Member Functions
abstract int evaluate (IParserProvider w) throws InvalidArgumentsException
Detailed Description
Base class for the tree that is built to represent an expression.
Author
Jonathan Schmidt
Definition at line 13 of file SyntaxNode.java.
Member Function Documentation
abstract int parser.nodes.SyntaxNode.evaluate (IParserProvider w) throws InvalidArgumentsException abstract
Evaluates the current node of the expression.
Parameters
w The active workspace.
Returns
The integer value of this expression.
Exceptions
InvalidArgumentsException Throws when there is an argument error.
Referenced by parser.commands.math.Difference.evaluate(), parser.commands.math.Minus.evaluate(), parser.commands.turtle.commands.Left.evaluate(), parser.commands.turtle.commands.Right.evaluate(), parser.commands.turtle.commands.SetHeading.evaluate(), parser.commands.turtle.commands.Towards.evaluate(), parser.commands.turtle.commands.SetPenColor.evaluate(), parser.commands.turtle.commands.SetPenSize.evaluate(), parser.commands.turtle.commands.SetPosition.evaluate(), parser.commands.turtle.commands.SetShape.evaluate(), parser.commands.math.Product.evaluate(), parser.commands.view.SetBackground.evaluate(), parser.commands.math.Sum.evaluate(), parser.commands.turtle.commands.Backward.evaluate(), parser.commands.turtle.commands.Forward.evaluate(), parser.commands.other.IfElse.evaluate(), parser.commands.other.If.evaluate(), parser.commands.math.Remainder.evaluate(), parser.commands.other.Make.evaluate(), parser.commands.math.Quotient.evaluate(), parser.commands.math.Random.evaluate(), parser.commands.other.Repeat.evaluate(), parser.commands.workspace.Ask.evaluate(), parser.commands.view.SetPalette.evaluate(), parser.commands.other.DoTimes.evaluate(), parser.commands.workspace.AskWith.evaluate(), and parser.commands.other.For.evaluate().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/Nodes/SyntaxNode.java