sLogo: parser.nodes.NodeInformation Class Reference
parser.nodes.NodeInformation Class Reference
Public Member Functions
NodeInformation (String name, ResourceBundle info)
String getName ()
String getDesc ()
Class<?> getType ()
int getArgs ()
boolean match (String token)
boolean equals (Object o)
String getToken ()
void setToken (String token)
Object clone ()
void setShouldCreate (boolean create)
boolean shouldCreate ()
Private Member Functions
NodeInformation (String name, String[] patterns, Class<?> clazz, int args, String desc, String token)
String getKey (String field)
Private Attributes
int myArgs
Class<?> myClass
String[] myPatterns
String myDesc
String myName
String myToken
boolean myshouldCreate = true
Static Private Attributes
static final String PROP_TOKEN = "token"
static final String PROP_CLASS = "class"
static final String PROP_ARGS = "args"
static final String PROP_DESC = "desc"
Detailed Description
This class represents the information that is stored in the properties file. This is all the information that is required to generate a new node.
Author
Jonathan Schmidt
Definition at line 15 of file NodeInformation.java.
Constructor & Destructor Documentation
parser.nodes.NodeInformation.NodeInformation (String name, String[] patterns, Class<?> clazz, int args, String desc, String token) private
Definition at line 31 of file NodeInformation.java.
Referenced by parser.nodes.NodeInformation.clone().
parser.nodes.NodeInformation.NodeInformation (String name, ResourceBundle info)
Creates the Node Information for a specified entry in the resource bundle. Searches the Resource Bundle and assigns all the parameters. *
Parameters
name The name of the node.
info The resource bundle containing all the information.
Definition at line 52 of file NodeInformation.java.
References parser.nodes.NodeInformation.getKey(), parser.nodes.exceptions.NodeDefinitionException.MISSING_CLASS, and parser.nodes.exceptions.NodeDefinitionException.REQUIRED_PROPERTY.
Member Function Documentation
Object parser.nodes.NodeInformation.clone ()
This is used to clone the particular Node Information.
Definition at line 153 of file NodeInformation.java.
References parser.nodes.NodeInformation.NodeInformation().
Referenced by parser.SemanticsTable.getTokenClass().
boolean parser.nodes.NodeInformation.equals (Object o)
Definition at line 128 of file NodeInformation.java.
References parser.nodes.NodeInformation.match().
int parser.nodes.NodeInformation.getArgs ()
Returns
The number of arguments the node takes.
Definition at line 110 of file NodeInformation.java.
References parser.nodes.NodeInformation.myArgs.
String parser.nodes.NodeInformation.getDesc ()
Returns
The description of the node entry.
Definition at line 94 of file NodeInformation.java.
References parser.nodes.NodeInformation.myDesc.
String parser.nodes.NodeInformation.getKey (String field) private
Definition at line 78 of file NodeInformation.java.
Referenced by parser.nodes.NodeInformation.NodeInformation().
String parser.nodes.NodeInformation.getName ()
Returns
The name of the node entry.
Definition at line 86 of file NodeInformation.java.
References parser.nodes.NodeInformation.myName.
Referenced by parser.SemanticsChecker.evaluateExpression().
String parser.nodes.NodeInformation.getToken ()
Returns
the token
Definition at line 138 of file NodeInformation.java.
References parser.nodes.NodeInformation.myToken.
Referenced by parser.SemanticsChecker.createCustomCommand().
Class<?> parser.nodes.NodeInformation.getType ()
Returns
The Class of the node entry.
Definition at line 102 of file NodeInformation.java.
References parser.nodes.NodeInformation.myClass.
Referenced by parser.SemanticsChecker.createCustomCommand().
boolean parser.nodes.NodeInformation.match (String token)
Returns whether a provided token matches the current Node.
Parameters
token The token to match it to.
Returns
Definition at line 120 of file NodeInformation.java.
Referenced by parser.nodes.NodeInformation.equals().
void parser.nodes.NodeInformation.setShouldCreate (boolean create)
Set whether this node should be created into it's actual node.
Parameters
create Whether or not to create it.
Definition at line 162 of file NodeInformation.java.
Referenced by parser.SemanticsChecker.createCustomCommand().
void parser.nodes.NodeInformation.setToken (String token)
Parameters
token the token to set
Definition at line 145 of file NodeInformation.java.
Referenced by parser.SemanticsTable.getTokenClass().
boolean parser.nodes.NodeInformation.shouldCreate ()
Returns whether this node should be created into it's actual node.
Returns
Definition at line 171 of file NodeInformation.java.
References parser.nodes.NodeInformation.myshouldCreate.
Member Data Documentation
int parser.nodes.NodeInformation.myArgs private
Definition at line 22 of file NodeInformation.java.
Referenced by parser.nodes.NodeInformation.getArgs().
Class<?> parser.nodes.NodeInformation.myClass private
Definition at line 23 of file NodeInformation.java.
Referenced by parser.nodes.NodeInformation.getType().
String parser.nodes.NodeInformation.myDesc private
Definition at line 25 of file NodeInformation.java.
Referenced by parser.nodes.NodeInformation.getDesc().
String parser.nodes.NodeInformation.myName private
Definition at line 26 of file NodeInformation.java.
Referenced by parser.nodes.NodeInformation.getName().
String [] parser.nodes.NodeInformation.myPatterns private
Definition at line 24 of file NodeInformation.java.
boolean parser.nodes.NodeInformation.myshouldCreate = true private
Definition at line 29 of file NodeInformation.java.
Referenced by parser.nodes.NodeInformation.shouldCreate().
String parser.nodes.NodeInformation.myToken private
Definition at line 27 of file NodeInformation.java.
Referenced by parser.nodes.NodeInformation.getToken().
final String parser.nodes.NodeInformation.PROP_ARGS = "args" static private
Definition at line 19 of file NodeInformation.java.
final String parser.nodes.NodeInformation.PROP_CLASS = "class" static private
Definition at line 18 of file NodeInformation.java.
final String parser.nodes.NodeInformation.PROP_DESC = "desc" static private
Definition at line 20 of file NodeInformation.java.
final String parser.nodes.NodeInformation.PROP_TOKEN = "token" static private
Definition at line 17 of file NodeInformation.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/Nodes/NodeInformation.java