sLogo: parser.nodes.ListNode Class Reference
parser.nodes.ListNode Class Reference
Public Member Functions
ListNode (Deque< SyntaxNode > queue)
int evaluate (IParserProvider w) throws InvalidArgumentsException
List< SyntaxNode > getContents ()
Public Member Functions inherited from parser.nodes.SyntaxNode
abstract int evaluate (IParserProvider w) throws InvalidArgumentsException
Private Attributes
List< SyntaxNode > myContents
Detailed Description
This represents a list in the tree. It contains all the nodes that are in the list.
Author
Jonathan Schmidt
Definition at line 17 of file ListNode.java.
Constructor & Destructor Documentation
parser.nodes.ListNode.ListNode (Deque< SyntaxNode > queue)
Creates a List node from a queue of parameters. Reads in all the parameters until a list end node is found.
Parameters
queue The list of parameters.
Definition at line 27 of file ListNode.java.
Member Function Documentation
int parser.nodes.ListNode.evaluate (IParserProvider w) throws InvalidArgumentsException
Definition at line 39 of file ListNode.java.
Referenced by parser.commands.workspace.AskWith.evaluate(), and parser.nodes.CommandNode.evaluate().
List<SyntaxNode> parser.nodes.ListNode.getContents ()
Returns
the contents
Definition at line 50 of file ListNode.java.
References parser.nodes.ListNode.myContents.
Referenced by parser.commands.other.DoTimes.checkSyntax(), parser.commands.other.For.checkSyntax(), parser.commands.workspace.Ask.evaluate(), and parser.commands.other.For.evaluate().
Member Data Documentation
List<SyntaxNode> parser.nodes.ListNode.myContents private
Definition at line 19 of file ListNode.java.
Referenced by parser.nodes.ListNode.getContents().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/Nodes/ListNode.java