sLogo: view.components.LogoTable Class Reference
view.components.LogoTable Class Reference
Public Member Functions
LogoTable ()
boolean isCellEditable (int row, int col)
JComboBox getComboBox ()
void setLastRowEditable (boolean edit)
TableCellEditor getCellEditor (int row, int col)
Private Attributes
boolean lastRowEditable = false
JComboBox myEditableComboBox
TableCellEditor myComboEditor
Detailed Description
Table that handles this program's specs
Author
Henrique Moraes
Definition at line 17 of file LogoTable.java.
Constructor & Destructor Documentation
view.components.LogoTable.LogoTable ()
Definition at line 22 of file LogoTable.java.
Member Function Documentation
TableCellEditor view.components.LogoTable.getCellEditor (int row, int col)
Takes into account an editable combo box when a variable is being added
Definition at line 55 of file LogoTable.java.
References view.windows.VariablesWindow.SCOPE_INDEX.
JComboBox view.components.LogoTable.getComboBox ()
Returns
Combo Box associated with inclusion of new variable
Definition at line 36 of file LogoTable.java.
Referenced by view.windows.VariablesWindow.createNewListener(), and view.windows.VariablesWindow.createOkButton().
boolean view.components.LogoTable.isCellEditable (int row, int col)
Definition at line 28 of file LogoTable.java.
References view.windows.VariablesWindow.VALUE_INDEX.
void view.components.LogoTable.setLastRowEditable (boolean edit)
Parameters
edit sets whether the last row is editable or not
Definition at line 43 of file LogoTable.java.
Referenced by view.windows.VariablesWindow.createNewListener(), and view.windows.VariablesWindow.createOkButton().
Member Data Documentation
boolean view.components.LogoTable.lastRowEditable = false private
Definition at line 18 of file LogoTable.java.
TableCellEditor view.components.LogoTable.myComboEditor private
Definition at line 20 of file LogoTable.java.
JComboBox view.components.LogoTable.myEditableComboBox private
Definition at line 19 of file LogoTable.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/view/components/LogoTable.java