sLogo: parser.commands.other.To Class Reference
parser.commands.other.To Class Reference
Public Member Functions
To (Deque< SyntaxNode > queue)
int evaluate (IParserProvider w) throws InvalidArgumentsException
Public Member Functions inherited from parser.nodes.TernaryNode
TernaryNode (SyntaxNode left, SyntaxNode middle, SyntaxNode right)
TernaryNode (Deque< SyntaxNode > queue)
SyntaxNode getMiddle ()
Public Member Functions inherited from parser.nodes.BinaryNode
BinaryNode (SyntaxNode left, SyntaxNode right)
BinaryNode (Deque< SyntaxNode > queue)
SyntaxNode getLeft ()
SyntaxNode getRight ()
Public Member Functions inherited from parser.nodes.ParameterNode
int getParameterCount ()
Public Member Functions inherited from parser.nodes.SyntaxNode
abstract int evaluate (IParserProvider w) throws InvalidArgumentsException
Private Member Functions
void checkSyntax () throws InvalidArgumentsException
Static Private Attributes
static final String FUNCTIONS_PARAM
static final String VAR_PARM = "Second parameter is not a list of variables."
static final String COMMAND_PARAM = "First parameter is not the name of a command."
Additional Inherited Members
Protected Member Functions inherited from parser.nodes.ParameterNode
void addParameter (int index, SyntaxNode node)
SyntaxNode getParameter (int index)
Detailed Description
Implements the To function. Creates a custom function.
Author
Jonathan Schmidt
Definition at line 20 of file To.java.
Constructor & Destructor Documentation
parser.commands.other.To.To (Deque< SyntaxNode > queue)
Creates To Command Node
Parameters
queue The list of nodes that come before this command
Definition at line 32 of file To.java.
Member Function Documentation
void parser.commands.other.To.checkSyntax () throws InvalidArgumentsException private
Definition at line 48 of file To.java.
References parser.nodes.BinaryNode.getLeft(), parser.nodes.TernaryNode.getMiddle(), and parser.nodes.BinaryNode.getRight().
Referenced by parser.commands.other.To.evaluate().
int parser.commands.other.To.evaluate (IParserProvider w) throws InvalidArgumentsException
Definition at line 37 of file To.java.
References parser.CustomCommand.addParserInfo(), parser.commands.other.To.checkSyntax(), parser.nodes.BinaryNode.getLeft(), parser.nodes.TernaryNode.getMiddle(), and parser.nodes.BinaryNode.getRight().
Member Data Documentation
final String parser.commands.other.To.COMMAND_PARAM = "First parameter is not the name of a command." static private
Definition at line 25 of file To.java.
final String parser.commands.other.To.FUNCTIONS_PARAM static private
Initial value:
=
            "Third parameter is not a list of functions to be run."
Definition at line 22 of file To.java.
final String parser.commands.other.To.VAR_PARM = "Second parameter is not a list of variables." static private
Definition at line 24 of file To.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/commands/other/To.java