sLogo: controller.Controller Class Reference
controller.Controller Class Reference
Public Member Functions
Controller ()
void processCommand (String command)
ActionListener createRunCommandListener ()
JMenuBar createJMenuBar ()
void loadWorkspace (Reader r) throws IOException
void processFile (Scanner inputFile)
Static Public Attributes
static final String USER_DIR = "user.dir"
static final String DEFAULT_RESOURCE_PACKAGE = "resources."
static final ResourceBundle RESOURCE
static final ResourceBundle RESOURCE_ERROR
Static Protected Attributes
static final String DEFAULT_URL
static final String HELP_TITLE = "Command Description for SLogo"
static final Object[] DEFAULT_PEN_COLOR_OPTION = { "red", "blue", "black" }
Private Member Functions
Workspace getWorkspace ()
JMenu createFileMenu ()
void createFileCommands (JMenu menu)
void createQuitCommand (JMenu menu)
JMenu createCommandMenu ()
void createPhysicalCommands (JMenu menu)
void createVisualCommands (JMenu menu)
JMenu createSettingMenu ()
MouseListener createTellMenuListener (final JMenu menu)
ItemListener createCheckBoxItemListener (final StayOpenCheckBoxMenuItem item)
JMenu createHelpMenu ()
JMenu createEditMenu ()
Private Attributes
int DEFAULT_MOVE_VALUE = 100
int DEFAULT_TURN_VALUE = 90
Parser myParser
WorkspaceHandler myWorkHandler
JFileChooser myChooser
InputField myInputField
Static Private Attributes
static final String LANGUAGE = "English"
static final int INPUT_FIELD_SIZE = 70
Detailed Description
Holds list of all workspaces, able to create new workspace Receives input from view and pass them to Parser Receives parsed input and send it to Executor with current workspace as parameter.
Author
Xu Rui, Henrique Moraes, Ziqiang Huang
Definition at line 53 of file Controller.java.
Constructor & Destructor Documentation
controller.Controller.Controller ()
Constructor for controller responsible for initializing the view and the parser
Definition at line 78 of file Controller.java.
References controller.Controller.createJMenuBar(), and controller.Controller.createRunCommandListener().
Member Function Documentation
ItemListener controller.Controller.createCheckBoxItemListener (final StayOpenCheckBoxMenuItem item) private
Parameters
item menu item to add the listener
Returns
item listener for this menu item
Definition at line 484 of file Controller.java.
References controller.Workspace.activateTurtle(), controller.Workspace.deactivateTurtle(), and controller.Controller.getWorkspace().
Referenced by controller.Controller.createTellMenuListener().
JMenu controller.Controller.createCommandMenu () private
Creates the command menu for the Menu Bar, this menu is created in control because it handles turtle instances that need to be separated from the view
Returns
Command menu for the view
Definition at line 229 of file Controller.java.
References controller.Controller.createPhysicalCommands(), and controller.Controller.createVisualCommands().
Referenced by controller.Controller.createJMenuBar().
JMenu controller.Controller.createEditMenu () private
Creates Edit menu with undo and redo options.
Returns
help Menu option
Definition at line 531 of file Controller.java.
References controller.Workspace.addHistory(), controller.Workspace.getUndoManager(), controller.Controller.getWorkspace(), controller.WSUndoManager.redo(), controller.Workspace.showError(), and controller.WSUndoManager.undo().
Referenced by controller.Controller.createJMenuBar().
void controller.Controller.createFileCommands (JMenu menu) private
Creates menu items that handles file manipulation such as creating a new one, saving and loading files
Returns
File menu for the view
Definition at line 170 of file Controller.java.
References view.WorkspaceHandler.createWorkspace(), controller.Controller.getWorkspace(), controller.Controller.loadWorkspace(), controller.Workspace.saveWorkspace(), and controller.Workspace.showError().
Referenced by controller.Controller.createFileMenu().
JMenu controller.Controller.createFileMenu () private
creates the File option on the menu bar
Returns
File Menu option
Definition at line 155 of file Controller.java.
References controller.Controller.createFileCommands(), and controller.Controller.createQuitCommand().
Referenced by controller.Controller.createJMenuBar().
JMenu controller.Controller.createHelpMenu () private
creates the help page option on the menu bar
Returns
help Menu option
Definition at line 507 of file Controller.java.
References controller.Controller.getWorkspace(), and controller.Workspace.showError().
Referenced by controller.Controller.createJMenuBar().
JMenuBar controller.Controller.createJMenuBar ()
Responsible for creating the menu bar, it needs to be called from window because once window calls pack(), the menu cannot be added The bar is created in controller so the view does not get access to important information from the model
Returns
menu bar for the program
Definition at line 140 of file Controller.java.
References controller.Controller.createCommandMenu(), controller.Controller.createEditMenu(), controller.Controller.createFileMenu(), controller.Controller.createHelpMenu(), and controller.Controller.createSettingMenu().
Referenced by controller.Controller.Controller().
void controller.Controller.createPhysicalCommands (JMenu menu) private
Adds physical turtle commands to the menu item, such as moving and turning
Parameters
menu menu to have the items added
Definition at line 245 of file Controller.java.
References controller.Workspace.addHistory(), controller.Workspace.getTurtleManager(), model.TurtleManager.getTurtles(), controller.Controller.getWorkspace(), and controller.Workspace.update().
Referenced by controller.Controller.createCommandMenu().
void controller.Controller.createQuitCommand (JMenu menu) private
Creates a command to quit the program
Returns
File menu for the view
Definition at line 213 of file Controller.java.
Referenced by controller.Controller.createFileMenu().
ActionListener controller.Controller.createRunCommandListener ()
set Listener to send the input string to controller whenever the run button or enter is pressed
Definition at line 112 of file Controller.java.
References view.components.InputField.getText(), controller.Controller.processCommand(), and view.components.InputField.setText().
Referenced by controller.Controller.Controller().
JMenu controller.Controller.createSettingMenu () private
creates the setting options on the menu bar, enabling user to set certain properties of the workspace, such as background image, turtle image, pen color, etc
Returns
Definition at line 354 of file Controller.java.
References controller.Workspace.addTurtle(), controller.Controller.createTellMenuListener(), controller.Workspace.getCanvas(), controller.Workspace.getColors(), controller.Workspace.getTurtleManager(), model.TurtleManager.getTurtles(), controller.Controller.getWorkspace(), view.Canvas.setBackgroundImage(), model.ColorManager.setColor(), and controller.Workspace.showError().
Referenced by controller.Controller.createJMenuBar().
MouseListener controller.Controller.createTellMenuListener (final JMenu menu) private
Parameters
menu menu to take checkbox items
Returns
mouse listener for this menu item
Definition at line 459 of file Controller.java.
References controller.Controller.createCheckBoxItemListener(), controller.Workspace.getAllTurtles(), controller.Workspace.getTurtleManager(), model.TurtleManager.getTurtles(), and controller.Controller.getWorkspace().
Referenced by controller.Controller.createSettingMenu().
void controller.Controller.createVisualCommands (JMenu menu) private
Adds visual turtle commands to the menu item, such as hiding itself and putting pen up or down
Parameters
menu menu to have the items added
Definition at line 299 of file Controller.java.
References controller.Workspace.addHistory(), controller.Workspace.getTurtleManager(), model.TurtleManager.getTurtles(), controller.Controller.getWorkspace(), and controller.Workspace.update().
Referenced by controller.Controller.createCommandMenu().
Workspace controller.Controller.getWorkspace () private
This method is set private so the Window does not have access to it
Returns
the current workspace selected on the tab used internally so this class can handle its functions
Definition at line 128 of file Controller.java.
References view.WorkspaceHandler.getWorkspace().
Referenced by controller.Controller.createCheckBoxItemListener(), controller.Controller.createEditMenu(), controller.Controller.createFileCommands(), controller.Controller.createHelpMenu(), controller.Controller.createPhysicalCommands(), controller.Controller.createSettingMenu(), controller.Controller.createTellMenuListener(), controller.Controller.createVisualCommands(), controller.Controller.processCommand(), and controller.Controller.processFile().
void controller.Controller.loadWorkspace (Reader r) throws IOException
Loads a file of variable and command to a current workspace.
Definition at line 565 of file Controller.java.
References controller.Controller.processFile().
Referenced by controller.Controller.createFileCommands().
void controller.Controller.processCommand (String command)
Parses command using parser, executes every command, update workspace command list
Parameters
command string in input Text Field
Definition at line 91 of file Controller.java.
References controller.Workspace.addExecutableHistory(), controller.Workspace.addHistory(), controller.Workspace.execute(), parser.SemanticsTable.getInstance(), controller.Controller.getWorkspace(), parser.Parser.parseCommand(), parser.SemanticsTable.setContext(), and controller.Workspace.showError().
Referenced by controller.Controller.createRunCommandListener().
void controller.Controller.processFile (Scanner inputFile)
Parses file using parser, executes every command in file
Parameters
input
Definition at line 576 of file Controller.java.
References controller.Workspace.execute(), parser.SemanticsTable.getInstance(), controller.Controller.getWorkspace(), parser.Parser.parseCommand(), parser.SemanticsTable.setContext(), and controller.Workspace.showError().
Referenced by controller.Controller.loadWorkspace().
Member Data Documentation
int controller.Controller.DEFAULT_MOVE_VALUE = 100 private
Definition at line 55 of file Controller.java.
final Object [] controller.Controller.DEFAULT_PEN_COLOR_OPTION = { "red", "blue", "black" } static protected
Definition at line 62 of file Controller.java.
final String controller.Controller.DEFAULT_RESOURCE_PACKAGE = "resources." static
Definition at line 58 of file Controller.java.
int controller.Controller.DEFAULT_TURN_VALUE = 90 private
Definition at line 56 of file Controller.java.
final String controller.Controller.DEFAULT_URL static protected
Initial value:
=
            "http://www.cs.duke.edu/courses/spring13/compsci308/assign/03_slogo/commands.php"
Definition at line 59 of file Controller.java.
final String controller.Controller.HELP_TITLE = "Command Description for SLogo" static protected
Definition at line 61 of file Controller.java.
final int controller.Controller.INPUT_FIELD_SIZE = 70 static private
Definition at line 67 of file Controller.java.
final String controller.Controller.LANGUAGE = "English" static private
Definition at line 54 of file Controller.java.
JFileChooser controller.Controller.myChooser private
Definition at line 71 of file Controller.java.
InputField controller.Controller.myInputField private
Definition at line 72 of file Controller.java.
Parser controller.Controller.myParser private
Definition at line 69 of file Controller.java.
WorkspaceHandler controller.Controller.myWorkHandler private
Definition at line 70 of file Controller.java.
final ResourceBundle controller.Controller.RESOURCE static
Initial value:
= ResourceBundle
            .getBundle(DEFAULT_RESOURCE_PACKAGE + LANGUAGE)
Definition at line 63 of file Controller.java.
Referenced by view.windows.SettingsWindow.createButtonPanel(), view.windows.LogoListWindow.createClearPanel(), view.windows.SettingsWindow.createTitlePanel(), view.windows.GraphicsSettingsWindow.GraphicsSettingsWindow(), view.windows.VariablesWindow.VariablesWindow(), and view.Window.Window().
final ResourceBundle controller.Controller.RESOURCE_ERROR static
Initial value:
= ResourceBundle
            .getBundle(DEFAULT_RESOURCE_PACKAGE + "error.Error" + LANGUAGE)
Definition at line 65 of file Controller.java.
Referenced by view.windows.GraphicsSettingsWindow.addOkButtonListener(), parser.VariableManager.addToScope(), view.windows.VariablesWindow.createOkButton(), parser.VariableManager.removeVariable(), view.windows.VariablesWindow.setTableListener(), and controller.Workspace.Workspace().
final String controller.Controller.USER_DIR = "user.dir" static
Definition at line 57 of file Controller.java.
Referenced by view.windows.GraphicsSettingsWindow.GraphicsSettingsWindow().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/controller/Controller.java