sLogo: view.components.ErrorBox Class Reference
view.components.ErrorBox Class Reference abstract
Static Public Member Functions
static void showError (Error e)
static void setWindow (Window w)
Static Public Attributes
static final ResourceBundle ERROR_RESOURCE
Static Private Attributes
static Window WINDOW = null
static final String DEFAULT_ERROR_RESOURCE_PACKAGE = "resources.error."
Detailed Description
Definition at line 10 of file ErrorBox.java.
Member Function Documentation
static void view.components.ErrorBox.setWindow (Window w) static
Definition at line 27 of file ErrorBox.java.
Referenced by view.Window.Window().
static void view.components.ErrorBox.showError (Error e) static
shows an error on a pop up window
Parameters
e
Definition at line 21 of file ErrorBox.java.
References view.components.Error.getMessage().
Referenced by model.TurtleManager.addTurtleImage(), model.TurtleManager.setImage(), and model.TurtleManager.setImageRelative().
Member Data Documentation
final String view.components.ErrorBox.DEFAULT_ERROR_RESOURCE_PACKAGE = "resources.error." static private
Definition at line 12 of file ErrorBox.java.
final ResourceBundle view.components.ErrorBox.ERROR_RESOURCE static
Initial value:
=
            ResourceBundle.getBundle(DEFAULT_ERROR_RESOURCE_PACKAGE + "ErrorEnglish")
Definition at line 13 of file ErrorBox.java.
Window view.components.ErrorBox.WINDOW = null static private
Definition at line 11 of file ErrorBox.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/view/components/ErrorBox.java