sLogo: parser.SemanticsTable Class Reference
parser.SemanticsTable Class Reference
Public Member Functions
SemanticsTable ()
NodeInformation getTokenClass (String token)
void setContext (IParserProvider context)
void registerCustomCommand (CustomCommand c)
CustomCommand getCommand (String name)
Static Public Member Functions
static SemanticsTable getInstance ()
Private Member Functions
void buildMap ()
Private Attributes
ResourceBundle myResource
IParserProvider myContext
List< NodeInformation > myNodeList
Static Private Attributes
static final String PARSER_RESOURCES = "parser.resources."
static final String SEMANTICS_FILE = "tokens"
static final Locale DEFAULT_REGION = Locale.ENGLISH
static final String TOKEN_LIST = "tokens"
static final String LIST_SEPERATOR = ","
static SemanticsTable instance = null
Detailed Description
The Semantics Table stores all the different nodes that can be created from commands that are entered. It links these to the format that the commands are in so that new instances of a node can be created.
Author
Jonathan Schmidt
Definition at line 19 of file SemanticsTable.java.
Constructor & Destructor Documentation
parser.SemanticsTable.SemanticsTable ()
Creates a new instance of the Semantics Table and loads the properties file.
Definition at line 36 of file SemanticsTable.java.
References parser.SemanticsTable.buildMap().
Referenced by parser.SemanticsTable.getInstance().
Member Function Documentation
void parser.SemanticsTable.buildMap () private
Reads in every item in the properties file and turns it into a Node Information. Builds the list of nodes that can be created.
Definition at line 45 of file SemanticsTable.java.
Referenced by parser.SemanticsTable.SemanticsTable().
CustomCommand parser.SemanticsTable.getCommand (String name)
Returns a custom command from the current context
Parameters
name The name of the custom command
Returns
The custom command
Definition at line 127 of file SemanticsTable.java.
References parser.IParserProvider.getCommand().
Referenced by parser.nodes.CommandNode.CommandNode(), and parser.SemanticsChecker.createNode().
static SemanticsTable parser.SemanticsTable.getInstance () static
Returns the instance of the SemanticsTable
Returns
Singleton
Definition at line 68 of file SemanticsTable.java.
References parser.SemanticsTable.instance, and parser.SemanticsTable.SemanticsTable().
Referenced by parser.nodes.CommandNode.CommandNode(), controller.Controller.processCommand(), controller.Controller.processFile(), and parser.SemanticsChecker.SemanticsChecker().
NodeInformation parser.SemanticsTable.getTokenClass (String token)
Returns the Node Information for a specific token. This will be used to get information about what a token represents in this application.
Parameters
token The token of which the information is required.
Returns
Definition at line 88 of file SemanticsTable.java.
References parser.nodes.NodeInformation.clone(), and parser.nodes.NodeInformation.setToken().
Referenced by parser.SemanticsChecker.evaluateExpression().
void parser.SemanticsTable.registerCustomCommand (CustomCommand c)
Registers a custom command to the current context.
Parameters
c The custom command to register
Definition at line 115 of file SemanticsTable.java.
References parser.IParserProvider.addCommand().
Referenced by parser.SemanticsChecker.evaluateExpression().
void parser.SemanticsTable.setContext (IParserProvider context)
Set the Current Context of the Semantics Table This allows each context to have it's own custom commands.
Parameters
context The Context
Definition at line 106 of file SemanticsTable.java.
Referenced by controller.Controller.processCommand(), and controller.Controller.processFile().
Member Data Documentation
final Locale parser.SemanticsTable.DEFAULT_REGION = Locale.ENGLISH static private
Definition at line 22 of file SemanticsTable.java.
SemanticsTable parser.SemanticsTable.instance = null static private
Definition at line 26 of file SemanticsTable.java.
Referenced by parser.SemanticsTable.getInstance().
final String parser.SemanticsTable.LIST_SEPERATOR = "," static private
Definition at line 25 of file SemanticsTable.java.
IParserProvider parser.SemanticsTable.myContext private
Definition at line 29 of file SemanticsTable.java.
List<NodeInformation> parser.SemanticsTable.myNodeList private
Definition at line 31 of file SemanticsTable.java.
ResourceBundle parser.SemanticsTable.myResource private
Definition at line 28 of file SemanticsTable.java.
final String parser.SemanticsTable.PARSER_RESOURCES = "parser.resources." static private
Definition at line 20 of file SemanticsTable.java.
final String parser.SemanticsTable.SEMANTICS_FILE = "tokens" static private
Definition at line 21 of file SemanticsTable.java.
final String parser.SemanticsTable.TOKEN_LIST = "tokens" static private
Definition at line 24 of file SemanticsTable.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/SemanticsTable.java