sLogo: parser.commands.workspace.AskWith Class Reference
parser.commands.workspace.AskWith Class Reference
Public Member Functions
AskWith (Deque< SyntaxNode > queue)
int evaluate (IParserProvider w) throws InvalidArgumentsException
Public Member Functions inherited from parser.nodes.BinaryNode
BinaryNode (SyntaxNode left, SyntaxNode right)
BinaryNode (Deque< SyntaxNode > queue)
SyntaxNode getLeft ()
SyntaxNode getRight ()
Public Member Functions inherited from parser.nodes.ParameterNode
int getParameterCount ()
Public Member Functions inherited from parser.nodes.SyntaxNode
abstract int evaluate (IParserProvider w) throws InvalidArgumentsException
Private Member Functions
void checkSyntax () throws InvalidArgumentsException
Static Private Attributes
static final String COMMAND_LIST
static final String DETERMINE_LIST
Additional Inherited Members
Protected Member Functions inherited from parser.nodes.ParameterNode
void addParameter (int index, SyntaxNode node)
SyntaxNode getParameter (int index)
Detailed Description
Implements the Sum function. Returns the left parameter's value + right parameter's value.
Author
Jonathan Schmidt
Definition at line 23 of file AskWith.java.
Constructor & Destructor Documentation
parser.commands.workspace.AskWith.AskWith (Deque< SyntaxNode > queue)
Creates Ask With Command Node
Parameters
queue The list of nodes that come before this command
Definition at line 37 of file AskWith.java.
Member Function Documentation
void parser.commands.workspace.AskWith.checkSyntax () throws InvalidArgumentsException private
Definition at line 70 of file AskWith.java.
References parser.nodes.BinaryNode.getLeft(), and parser.nodes.BinaryNode.getRight().
Referenced by parser.commands.workspace.AskWith.evaluate().
int parser.commands.workspace.AskWith.evaluate (IParserProvider w) throws InvalidArgumentsException
Definition at line 42 of file AskWith.java.
References model.TurtleManager.activate(), parser.commands.workspace.AskWith.checkSyntax(), model.TurtleManager.clearActive(), model.TurtleManager.copyActive(), parser.nodes.SyntaxNode.evaluate(), parser.nodes.ListNode.evaluate(), model.TurtleManager.getAllTurtles(), parser.nodes.BinaryNode.getLeft(), and parser.nodes.BinaryNode.getRight().
Member Data Documentation
final String parser.commands.workspace.AskWith.COMMAND_LIST static private
Initial value:
=
            "Second parameter must be a list of commands to run on the turtles."
Definition at line 25 of file AskWith.java.
final String parser.commands.workspace.AskWith.DETERMINE_LIST static private
Initial value:
=
            "First parameter must be a list of commands to run in order to determine" +
                    " whether a turtle is valid to run the second paramter's commands on."
Definition at line 27 of file AskWith.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/commands/workspace/AskWith.java