sLogo: parser.SemanticsChecker Class Reference
parser.SemanticsChecker Class Reference
Public Member Functions
SemanticsChecker ()
List< SyntaxNode > evaluateExpression (List< String > tokens) throws InvalidSemanticsException
Private Member Functions
SyntaxNode createNode (String token, NodeInformation n, Deque< SyntaxNode > params) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, ClassDefinitionException, InvalidSemanticsException, InvalidArgumentsException
CustomCommand createCustomCommand (List< NodeInformation > nodeI, int pos) throws InvalidSemanticsException
Private Attributes
SemanticsTable myTable
Static Private Attributes
static final int NUMBER_TO_PARAMS = 3
static final String NOT_A_VALID_COMMAND = "%s is not a valid command."
static final String TO = "to"
Detailed Description
This class takes tokens and builds them into something that can be run by the application. These SyntaxNodes are created by reading in a properties file containing all the information about a node in the tree.
The nodes are then created using reflection. Some basic syntax checking is performed in the creation of these nodes.
Author
Jonathan Schmidt
Definition at line 30 of file SemanticsChecker.java.
Constructor & Destructor Documentation
parser.SemanticsChecker.SemanticsChecker ()
Creates an instance of the SemanticsChecker
Definition at line 40 of file SemanticsChecker.java.
References parser.SemanticsTable.getInstance().
Member Function Documentation
CustomCommand parser.SemanticsChecker.createCustomCommand (List< NodeInformation > nodeI, int pos) throws InvalidSemanticsException private
Definition at line 134 of file SemanticsChecker.java.
References parser.nodes.NodeInformation.getToken(), parser.nodes.NodeInformation.getType(), and parser.nodes.NodeInformation.setShouldCreate().
Referenced by parser.SemanticsChecker.evaluateExpression().
SyntaxNode parser.SemanticsChecker.createNode (String token, NodeInformation n, Deque< SyntaxNode > params) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, ClassDefinitionException, InvalidSemanticsException, InvalidArgumentsException private
Creates a Node using the specified information and reflection.
Parameters
token
n
params
Returns
Exceptions
InstantiationException
IllegalAccessException
IllegalArgumentException
InvocationTargetException
ClassDefinitionException
InvalidSemanticsException
InvalidArgumentsException
Definition at line 109 of file SemanticsChecker.java.
References parser.reflection.ReflectionHelper.createInstanceOf(), parser.SemanticsTable.getCommand(), and parser.nodes.exceptions.InvalidArgumentsException.INCORRECT_NUMBER_ARGS.
Referenced by parser.SemanticsChecker.evaluateExpression().
List<SyntaxNode> parser.SemanticsChecker.evaluateExpression (List< String > tokens) throws InvalidSemanticsException
Takes in a list of tokens of input and turns them into SyntaxNodes Builds trees and returns a list of all the roots of the trees.
Parameters
tokens a list of tokens that have been processed.
Returns
List of SyntaxNodes representing the roots of trees.
Exceptions
InvalidSemanticsException When there is an error in the tokens
Definition at line 52 of file SemanticsChecker.java.
References parser.SemanticsChecker.createCustomCommand(), parser.SemanticsChecker.createNode(), parser.nodes.NodeInformation.getName(), parser.SemanticsTable.getTokenClass(), and parser.SemanticsTable.registerCustomCommand().
Referenced by parser.Parser.parseCommand().
Member Data Documentation
SemanticsTable parser.SemanticsChecker.myTable private
Definition at line 35 of file SemanticsChecker.java.
final String parser.SemanticsChecker.NOT_A_VALID_COMMAND = "%s is not a valid command." static private
Definition at line 33 of file SemanticsChecker.java.
final int parser.SemanticsChecker.NUMBER_TO_PARAMS = 3 static private
Definition at line 32 of file SemanticsChecker.java.
final String parser.SemanticsChecker.TO = "to" static private
Definition at line 34 of file SemanticsChecker.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/SemanticsChecker.java