sLogo: parser.nodes.TokenNode Class Reference
parser.nodes.TokenNode Class Reference
Public Member Functions
TokenNode (String token)
int evaluate (IParserProvider w) throws InvalidArgumentsException
String getToken ()
Public Member Functions inherited from parser.nodes.SyntaxNode
abstract int evaluate (IParserProvider w) throws InvalidArgumentsException
Private Attributes
String myToken
Detailed Description
This class is used to store the current token we are dealing with on the stack. Used for elements that have no arguments.
Author
Jonathan Schmidt
Definition at line 14 of file TokenNode.java.
Constructor & Destructor Documentation
parser.nodes.TokenNode.TokenNode (String token)
Creates a Token Node from a String
Parameters
token The Token
Definition at line 23 of file TokenNode.java.
Referenced by parser.nodes.ListEndNode.ListEndNode(), and parser.nodes.ParamListEndNode.ParamListEndNode().
Member Function Documentation
int parser.nodes.TokenNode.evaluate (IParserProvider w) throws InvalidArgumentsException
Definition at line 28 of file TokenNode.java.
String parser.nodes.TokenNode.getToken ()
Returns the token.
Returns
the token
Definition at line 37 of file TokenNode.java.
References parser.nodes.TokenNode.myToken.
Referenced by parser.nodes.ListEndNode.ListEndNode(), and parser.nodes.ParamListEndNode.ParamListEndNode().
Member Data Documentation
String parser.nodes.TokenNode.myToken private
Definition at line 16 of file TokenNode.java.
Referenced by parser.nodes.TokenNode.getToken().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/Nodes/TokenNode.java