sLogo: view.Vector Class Reference
view.Vector Class Reference
Public Member Functions
Vector ()
Vector (double angle, double magnitude)
Vector (Point2D source, Point2D target)
Vector (Vector other)
void reset ()
double getMagnitude ()
double getRelativeMagnitude (Vector other)
void scale (double change)
void setMagnitude (double value)
double getDirection ()
double getAngleBetween (Vector other)
void turn (double change)
double getXChange ()
double getYChange ()
void sum (Vector other)
void difference (Vector other)
void negate ()
Vector average (Vector other)
boolean equals (Object vector)
String toString ()
Static Public Member Functions
static double distanceBetween (Point2D p1, Point2D p2)
static double distanceBetween (double dx, double dy)
static double angleBetween (Point2D p1, Point2D p2)
static double angleBetween (double dx, double dy)
static boolean fuzzyEquals (double a, double b)
Protected Member Functions
void setDirection (double value)
Private Attributes
double myAngle
double myMagnitude
Detailed Description
This class represents a mathematical vector as a direction and magnitude.
Note, this class has no relation to java.util.Vector!
Author
Robert C. Duvall
Definition at line 13 of file Vector.java.
Constructor & Destructor Documentation
view.Vector.Vector ()
Create a zero vector, i.e., with no magnitude.
Definition at line 22 of file Vector.java.
Referenced by view.Vector.average(), view.Vector.difference(), and view.Vector.equals().
view.Vector.Vector (double angle, double magnitude)
Create a vector in the given direction with the given magnitude.
Definition at line 29 of file Vector.java.
References view.Vector.setDirection(), and view.Vector.setMagnitude().
view.Vector.Vector (Point2D source, Point2D target)
Create a vector whose direction and magnitude are determined by direction and distance between the two given points.
Definition at line 38 of file Vector.java.
References view.Vector.angleBetween(), view.Vector.distanceBetween(), view.Vector.setDirection(), and view.Vector.setMagnitude().
view.Vector.Vector (Vector other)
Create a vector that is identical to the given other vector.
Definition at line 48 of file Vector.java.
References view.Vector.getDirection(), and view.Vector.getMagnitude().
Member Function Documentation
static double view.Vector.angleBetween (Point2D p1, Point2D p2) static
Returns the angle between the given two points
Definition at line 229 of file Vector.java.
Referenced by view.Vector.sum(), and view.Vector.Vector().
static double view.Vector.angleBetween (double dx, double dy) static
Returns the angle represented by the given dx and dy
Definition at line 236 of file Vector.java.
Vector view.Vector.average (Vector other)
Returns the average of this vector with the given other vector.
Definition at line 183 of file Vector.java.
References view.Vector.getDirection(), view.Vector.getMagnitude(), and view.Vector.Vector().
void view.Vector.difference (Vector other)
Subtracts the given vector from this vector.
Definition at line 165 of file Vector.java.
References view.Vector.negate(), view.Vector.sum(), and view.Vector.Vector().
static double view.Vector.distanceBetween (Point2D p1, Point2D p2) static
Returns the distance between given two points
Definition at line 215 of file Vector.java.
Referenced by view.Vector.sum(), and view.Vector.Vector().
static double view.Vector.distanceBetween (double dx, double dy) static
Returns the distance represented by the given dx and dy
Definition at line 222 of file Vector.java.
boolean view.Vector.equals (Object vector)
Return true if this vector has the same magnitude and direction as the given other vector.
Definition at line 193 of file Vector.java.
References view.Vector.fuzzyEquals(), view.Vector.getDirection(), view.Vector.getMagnitude(), and view.Vector.Vector().
static boolean view.Vector.fuzzyEquals (double a, double b) static
Returns true if two real values are approximately equal.
For more details, see http://www.ibm.com/developerworks/java/library/j-jtp0114/#N10255
This function exists in many add-on libraries, but not standard Java :(
Definition at line 249 of file Vector.java.
Referenced by view.Vector.equals().
double view.Vector.getAngleBetween (Vector other)
Returns the angle between this vector and the given other vector.
Definition at line 109 of file Vector.java.
References view.Vector.getDirection().
Referenced by view.Vector.getRelativeMagnitude().
double view.Vector.getDirection ()
Returns this vector's direction (in degrees).
Definition at line 99 of file Vector.java.
Referenced by view.Vector.average(), view.Vector.equals(), view.Vector.getAngleBetween(), view.Vector.getXChange(), view.Vector.getYChange(), view.Vector.toString(), view.Vector.turn(), and view.Vector.Vector().
double view.Vector.getMagnitude ()
Returns this vector's magnitude (in pixels).
Definition at line 63 of file Vector.java.
References view.Vector.myMagnitude.
Referenced by view.Vector.average(), view.Vector.equals(), view.Vector.getRelativeMagnitude(), view.Vector.getXChange(), view.Vector.getYChange(), view.Vector.scale(), view.Vector.toString(), and view.Vector.Vector().
double view.Vector.getRelativeMagnitude (Vector other)
Returns this vector's magnitude relative to the given other vector.
More formally, returns the magnitude of this vector projected onto the given other vector.
Definition at line 73 of file Vector.java.
References view.Vector.getAngleBetween(), and view.Vector.getMagnitude().
double view.Vector.getXChange ()
Returns the change in only the X direction represented by this vector.
Definition at line 130 of file Vector.java.
References view.Vector.getDirection(), and view.Vector.getMagnitude().
Referenced by view.Vector.sum(), and view.Location.translate().
double view.Vector.getYChange ()
Returns the change in only the Y direction represented by this vector.
Definition at line 137 of file Vector.java.
References view.Vector.getDirection(), and view.Vector.getMagnitude().
Referenced by view.Vector.sum(), and view.Location.translate().
void view.Vector.negate ()
Returns a vector of the same magnitude, but in the opposite direction as this vector.
Definition at line 176 of file Vector.java.
References view.Vector.turn().
Referenced by view.Vector.difference().
void view.Vector.reset ()
Reset this vector to zero.
Definition at line 55 of file Vector.java.
References view.Vector.setDirection(), and view.Vector.setMagnitude().
void view.Vector.scale (double change)
Scales this vector's magnitude by the given change value.
A value of 1 leaves the magnitude unchanged
Values less than 1 reduce the magnitude
Values greater than 1 increase the magnitude
Definition at line 85 of file Vector.java.
References view.Vector.getMagnitude(), and view.Vector.setMagnitude().
void view.Vector.setDirection (double value) protected
Sets this vector's direction to the given value.
Definition at line 123 of file Vector.java.
Referenced by view.Vector.reset(), view.Vector.sum(), view.Vector.turn(), and view.Vector.Vector().
void view.Vector.setMagnitude (double value)
Sets this vector's magnitude to the given value.
Definition at line 92 of file Vector.java.
Referenced by view.Vector.reset(), view.Vector.scale(), view.Vector.sum(), and view.Vector.Vector().
void view.Vector.sum (Vector other)
Adds the given vector to this vector.
Definition at line 144 of file Vector.java.
References view.Vector.angleBetween(), view.Vector.distanceBetween(), view.Vector.getXChange(), view.Vector.getYChange(), view.Vector.setDirection(), and view.Vector.setMagnitude().
Referenced by view.Vector.difference().
String view.Vector.toString ()
Returns this vector's values formatted as a string.
Definition at line 208 of file Vector.java.
References view.Vector.getDirection(), and view.Vector.getMagnitude().
void view.Vector.turn (double change)
Adjusts this vector's direction by the given change value.
Definition at line 116 of file Vector.java.
References view.Vector.getDirection(), and view.Vector.setDirection().
Referenced by view.Vector.negate().
Member Data Documentation
double view.Vector.myAngle private
Definition at line 15 of file Vector.java.
double view.Vector.myMagnitude private
Definition at line 17 of file Vector.java.
Referenced by view.Vector.getMagnitude().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/view/Vector.java