sLogo: model.ColorManager Class Reference
model.ColorManager Class Reference
Public Member Functions
ColorManager ()
void setColor (int index, Color c)
Color getColor (int index)
int getColorID (Color c)
Map< Integer, Color > getColorMap ()
Private Attributes
Map< Integer, Color > myPalette
Static Private Attributes
static final Color[] DEFAULT_COLORS
Detailed Description
Class to manage the storing of colors. Allows users to add colors and to retrieve colors.
Author
Jonathan Schmidt
Definition at line 16 of file ColorManager.java.
Constructor & Destructor Documentation
model.ColorManager.ColorManager ()
Definition at line 30 of file ColorManager.java.
References model.ColorManager.setColor().
Member Function Documentation
Color model.ColorManager.getColor (int index)
Definition at line 43 of file ColorManager.java.
Referenced by controller.Workspace.setBackground().
int model.ColorManager.getColorID (Color c)
Definition at line 49 of file ColorManager.java.
Map<Integer, Color> model.ColorManager.getColorMap ()
Definition at line 60 of file ColorManager.java.
References model.ColorManager.myPalette.
Referenced by view.windows.WorkspaceSettingsWindow.createColorPanel().
void model.ColorManager.setColor (int index, Color c)
Definition at line 38 of file ColorManager.java.
Referenced by model.ColorManager.ColorManager(), and controller.Controller.createSettingMenu().
Member Data Documentation
final Color [] model.ColorManager.DEFAULT_COLORS static private
Initial value:
= new Color[] { Color.WHITE,
                                                               Color.BLACK,
                                                               Color.RED,
                                                               Color.GREEN,
                                                               Color.BLUE,
                                                               Color.DARK_GRAY,
                                                               Color.LIGHT_GRAY,
                                                               Color.PINK
    }
Definition at line 18 of file ColorManager.java.
Map<Integer, Color> model.ColorManager.myPalette private
Definition at line 28 of file ColorManager.java.
Referenced by model.ColorManager.getColorMap().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/model/ColorManager.java