sLogo: model.TurtleManager Class Reference
model.TurtleManager Class Reference
Public Member Functions
TurtleManager ()
void activate (int index)
void activate (Collection< Integer > turtles)
void update ()
void addNew (int index)
void clearActive ()
void setImage (String path)
int activateOdd ()
int activateEven ()
void deactivateTurtle (int index)
void paint (Graphics2D pen)
void setHighlighted (boolean active)
void setStroke (Stroke stroke)
boolean getHighlighted ()
Map< Integer, Turtle > getTurtles ()
Map< Integer, Turtle > getAllTurtles ()
Turtle getCurrent ()
void setCurrent (Turtle current)
List< Integer > copyActive ()
void setStrokeType (Strokes s)
void addTurtleImage (int index, String imageDir)
Object getTurtleImage (int shapeid)
int getShape (BufferedImage image)
Static Public Attributes
static final String DEFAULT_IMAGE_PATH = "/images/turtleSideways.png"
static final Color INITIAL_GRAD_COLOR = new Color(255, 170, 0)
static final Color FINAL_GRAD_COLOR = new Color(255, 255, 0)
Package Functions
public< T > T execute (String commandName, Object...args)
Private Member Functions
int addActive (int addMethod)
Turtle createTurtle (int index)
void setImageRelative (String path)
void activateTurtle (int index)
Private Attributes
Map< Integer, Turtle > myActiveTurtles
Map< Integer, Turtle > myTurtles
Map< Integer, BufferedImage > myTurtleImages
BufferedImage myImage
int lastIndex = 0
boolean highlightEnabled = false
Stroke myStroke
Turtle myCurrent
Static Private Attributes
static final Stroke ACTIVE_STROKE
static final int ADD_ODD = -1
static final int ADD_EVEN = -2
Detailed Description
Manages all the properties and state of the turtles from a specific workspace
Author
Henrique Moraes,Ziqiang Huang, Jonathan Schmidt
Definition at line 33 of file TurtleManager.java.
Constructor & Destructor Documentation
model.TurtleManager.TurtleManager ()
Definition at line 53 of file TurtleManager.java.
References model.TurtleManager.activate(), model.Pen.DEFAULT_STROKE, and model.TurtleManager.setImageRelative().
Member Function Documentation
void model.TurtleManager.activate (int index)
Activates the turtle at the specified index, if turtle does not exist create a new one
Parameters
index index to specify the turtle
Definition at line 68 of file TurtleManager.java.
References model.TurtleManager.activateTurtle(), and model.TurtleManager.addNew().
Referenced by model.TurtleManager.activate(), controller.Workspace.activateTurtle(), parser.commands.workspace.Ask.evaluate(), parser.commands.workspace.AskWith.evaluate(), and model.TurtleManager.TurtleManager().
void model.TurtleManager.activate (Collection< Integer > turtles)
Parameters
turtles Collection of turtles to be activated
Definition at line 78 of file TurtleManager.java.
References model.TurtleManager.activate().
int model.TurtleManager.activateEven ()
Activates Even indexed turtles
Definition at line 185 of file TurtleManager.java.
References model.TurtleManager.addActive().
int model.TurtleManager.activateOdd ()
Activates Odd indexed turtles
Definition at line 178 of file TurtleManager.java.
References model.TurtleManager.addActive().
void model.TurtleManager.activateTurtle (int index) private
Activates the turtle specified by the index
Definition at line 192 of file TurtleManager.java.
Referenced by model.TurtleManager.activate(), and model.TurtleManager.addActive().
int model.TurtleManager.addActive (int addMethod) private
Parameters
addMethod type of activation (Odd or even)
Returns
id of last activated turtle
Definition at line 89 of file TurtleManager.java.
References model.TurtleManager.activateTurtle(), and model.TurtleManager.clearActive().
Referenced by model.TurtleManager.activateEven(), and model.TurtleManager.activateOdd().
void model.TurtleManager.addNew (int index)
Adds a new turtle with the specified index
Parameters
index index o the turtle
Definition at line 117 of file TurtleManager.java.
References model.TurtleManager.createTurtle(), and model.Turtle.setStroke().
Referenced by model.TurtleManager.activate(), and controller.Workspace.addTurtle().
void model.TurtleManager.addTurtleImage (int index, String imageDir)
Adds the specified image to the collection of turtle images
Parameters
index of the image
imageDir Image directory
Definition at line 342 of file TurtleManager.java.
References view.components.Error.INVALID_IMAGE, and view.components.ErrorBox.showError().
Referenced by controller.Workspace.addTurtleImage().
void model.TurtleManager.clearActive ()
Clears the active turtles for this workspace;
Definition at line 127 of file TurtleManager.java.
Referenced by model.TurtleManager.addActive(), parser.commands.workspace.Ask.evaluate(), and parser.commands.workspace.AskWith.evaluate().
List<Integer> model.TurtleManager.copyActive ()
Returns a copy of the active turtles
Returns
Definition at line 290 of file TurtleManager.java.
References model.TurtleManager.getTurtles().
Referenced by parser.commands.workspace.Ask.evaluate(), and parser.commands.workspace.AskWith.evaluate().
Turtle model.TurtleManager.createTurtle (int index) private
Creates a new turtle with parameters specified by this manager
Returns
Turtle with manager settings
Definition at line 136 of file TurtleManager.java.
References model.Turtle.setImage().
Referenced by model.TurtleManager.addNew().
void model.TurtleManager.deactivateTurtle (int index)
Activates the turtle specified by the index
Definition at line 201 of file TurtleManager.java.
Referenced by controller.Workspace.deactivateTurtle().
public<T> T model.TurtleManager.execute (String commandName, Object... args) package
Execute the provided method name on every active turtle
Parameters
commandName The method to run on the turtle.
args The arguments that the methods takes.
Returns
T the type of result
Definition at line 304 of file TurtleManager.java.
References parser.reflection.ReflectionHelper.findMethod(), and model.TurtleManager.update().
Map<Integer, Turtle> model.TurtleManager.getAllTurtles ()
Returns
All the turtles associated with this manager
Definition at line 267 of file TurtleManager.java.
References model.TurtleManager.myTurtles.
Referenced by parser.commands.workspace.AskWith.evaluate(), and controller.Workspace.getAllTurtles().
Turtle model.TurtleManager.getCurrent ()
Returns
the current Turtle
Definition at line 274 of file TurtleManager.java.
References model.TurtleManager.myCurrent.
Referenced by controller.Workspace.getTurtle().
boolean model.TurtleManager.getHighlighted ()
Returns
active boolean representing whether currently active turtles should be highlighted or not
Definition at line 253 of file TurtleManager.java.
References model.TurtleManager.highlightEnabled.
Referenced by controller.Workspace.getHighlighted().
int model.TurtleManager.getShape (BufferedImage image)
Parameters
image The Image of that the ID is required for.
Returns
id of this image
Definition at line 369 of file TurtleManager.java.
Object model.TurtleManager.getTurtleImage (int shapeid)
Parameters
shapeid The ID of the shape
Returns
Buffered image associated with the id
Definition at line 360 of file TurtleManager.java.
Map<Integer, Turtle> model.TurtleManager.getTurtles ()
Returns
Currently active turtles associated with this manager
Definition at line 260 of file TurtleManager.java.
References model.TurtleManager.myActiveTurtles.
Referenced by model.TurtleManager.copyActive(), controller.Controller.createPhysicalCommands(), controller.Controller.createSettingMenu(), controller.Controller.createTellMenuListener(), controller.Controller.createVisualCommands(), controller.WSUndoManager.undo(), and view.windows.InformationView.update().
void model.TurtleManager.paint (Graphics2D pen)
Paints each turtle and stamp from the workspace and highlights the active ones
Implements model.Paintable.
Definition at line 210 of file TurtleManager.java.
References model.TurtleManager.FINAL_GRAD_COLOR, model.Turtle.getHeight(), util.Location.getIntX(), util.Location.getIntY(), model.Turtle.getPaintingPoint(), model.Turtle.getWidth(), model.TurtleManager.highlightEnabled, model.TurtleManager.INITIAL_GRAD_COLOR, and model.Turtle.paint().
Referenced by controller.Workspace.paint().
void model.TurtleManager.setCurrent (Turtle current)
Parameters
current the Turtle to be set as current
Definition at line 281 of file TurtleManager.java.
void model.TurtleManager.setHighlighted (boolean active)
Parameters
active boolean representing whether currently active turtles should be highlighted or not
Definition at line 232 of file TurtleManager.java.
References model.TurtleManager.update().
Referenced by controller.Workspace.setHighlighted().
void model.TurtleManager.setImage (String path)
Sets image based on an absolute path
Parameters
path
Definition at line 161 of file TurtleManager.java.
References view.components.Error.INVALID_IMAGE, view.components.ErrorBox.showError(), and model.TurtleManager.update().
Referenced by controller.Workspace.setImage().
void model.TurtleManager.setImageRelative (String path) private
sets image Based on a relative path
Parameters
path
Definition at line 147 of file TurtleManager.java.
References view.components.Error.INVALID_IMAGE, and view.components.ErrorBox.showError().
Referenced by model.TurtleManager.TurtleManager().
void model.TurtleManager.setStroke (Stroke stroke)
Parameters
stroke Stroke to be set on each active turtle
Definition at line 240 of file TurtleManager.java.
Referenced by controller.Workspace.setStroke().
void model.TurtleManager.setStrokeType (Strokes s)
Parameters
s stroke type to be set at the turtles
Definition at line 329 of file TurtleManager.java.
Referenced by controller.Workspace.setStrokeType().
void model.TurtleManager.update ()
Updates this object by notifying its observers and painting the turtles
Definition at line 107 of file TurtleManager.java.
Referenced by model.TurtleManager.execute(), controller.WSUndoManager.redo(), model.TurtleManager.setHighlighted(), model.TurtleManager.setImage(), controller.WSUndoManager.undo(), and controller.Workspace.update().
Member Data Documentation
final Stroke model.TurtleManager.ACTIVE_STROKE static private
Initial value:
= new BasicStroke(3, BasicStroke.CAP_ROUND,
                                                                BasicStroke.JOIN_ROUND)
Definition at line 37 of file TurtleManager.java.
final int model.TurtleManager.ADD_EVEN = -2 static private
Definition at line 41 of file TurtleManager.java.
final int model.TurtleManager.ADD_ODD = -1 static private
Definition at line 40 of file TurtleManager.java.
final String model.TurtleManager.DEFAULT_IMAGE_PATH = "/images/turtleSideways.png" static
Definition at line 34 of file TurtleManager.java.
final Color model.TurtleManager.FINAL_GRAD_COLOR = new Color(255, 255, 0) static
Definition at line 36 of file TurtleManager.java.
Referenced by model.TurtleManager.paint().
boolean model.TurtleManager.highlightEnabled = false private
Definition at line 48 of file TurtleManager.java.
Referenced by model.TurtleManager.getHighlighted(), and model.TurtleManager.paint().
final Color model.TurtleManager.INITIAL_GRAD_COLOR = new Color(255, 170, 0) static
Definition at line 35 of file TurtleManager.java.
Referenced by model.TurtleManager.paint().
int model.TurtleManager.lastIndex = 0 private
Definition at line 47 of file TurtleManager.java.
Map<Integer, Turtle> model.TurtleManager.myActiveTurtles private
Definition at line 43 of file TurtleManager.java.
Referenced by model.TurtleManager.getTurtles().
Turtle model.TurtleManager.myCurrent private
Definition at line 51 of file TurtleManager.java.
Referenced by model.TurtleManager.getCurrent().
BufferedImage model.TurtleManager.myImage private
Definition at line 46 of file TurtleManager.java.
Stroke model.TurtleManager.myStroke private
Definition at line 49 of file TurtleManager.java.
Map<Integer, BufferedImage> model.TurtleManager.myTurtleImages private
Definition at line 45 of file TurtleManager.java.
Map<Integer, Turtle> model.TurtleManager.myTurtles private
Definition at line 44 of file TurtleManager.java.
Referenced by model.TurtleManager.getAllTurtles().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/model/TurtleManager.java