sLogo: model.Pen Class Reference
model.Pen Class Reference
Public Member Functions
void addLine (Location initialLocation, Location finalLocation)
Pen ()
void setPenColor (Color color)
Color getPenColor ()
void paint (Graphics2D pen)
void setPenWriting (boolean write)
void setStroke (Stroke stroke)
Stroke getStroke ()
boolean isPenWriting ()
void setStrokeType (Strokes s)
Strokes getStrokeType ()
Static Public Attributes
static final Stroke DEFAULT_STROKE = new BasicStroke(1)
Package Attributes
List< PenLine > myLines
Private Attributes
boolean penWriting = true
Color myCurrentColor = Color.BLACK
Stroke myStroke
Strokes myStrokeType
Detailed Description
Pen object that hold the lines that has to be drawn on the canvas
Author
Henrique Moraes
Definition at line 20 of file Pen.java.
Constructor & Destructor Documentation
model.Pen.Pen ()
Definition at line 34 of file Pen.java.
References model.Pen.DEFAULT_STROKE.
Member Function Documentation
void model.Pen.addLine (Location initialLocation, Location finalLocation)
Definition at line 29 of file Pen.java.
Referenced by model.Turtle.move().
Color model.Pen.getPenColor ()
Definition at line 43 of file Pen.java.
References model.Pen.myCurrentColor.
Referenced by model.Turtle.getPenColor().
Stroke model.Pen.getStroke ()
Definition at line 64 of file Pen.java.
References model.Pen.myStroke.
Strokes model.Pen.getStrokeType ()
Definition at line 76 of file Pen.java.
References model.Pen.myStrokeType.
Referenced by model.Turtle.setPenSize().
boolean model.Pen.isPenWriting ()
Definition at line 68 of file Pen.java.
References model.Pen.penWriting.
Referenced by model.Turtle.isPenWriting().
void model.Pen.paint (Graphics2D pen)
Definition at line 47 of file Pen.java.
Referenced by model.Turtle.paint().
void model.Pen.setPenColor (Color color)
Definition at line 39 of file Pen.java.
Referenced by model.Turtle.setColor().
void model.Pen.setPenWriting (boolean write)
Definition at line 53 of file Pen.java.
Referenced by model.Turtle.setPenWriting().
void model.Pen.setStroke (Stroke stroke)
Sets the stroke for the pen of this turtle
Definition at line 60 of file Pen.java.
Referenced by model.Turtle.setPenSize(), and model.Turtle.setStroke().
void model.Pen.setStrokeType (Strokes s)
Definition at line 72 of file Pen.java.
Referenced by model.Turtle.setStrokeType().
Member Data Documentation
final Stroke model.Pen.DEFAULT_STROKE = new BasicStroke(1) static
Definition at line 21 of file Pen.java.
Referenced by model.Pen.Pen(), util.PenLine.PenLine(), and model.TurtleManager.TurtleManager().
Color model.Pen.myCurrentColor = Color.BLACK private
Definition at line 25 of file Pen.java.
Referenced by model.Pen.getPenColor().
List<PenLine> model.Pen.myLines package
Definition at line 23 of file Pen.java.
Referenced by model.Turtle.clear().
Stroke model.Pen.myStroke private
Definition at line 26 of file Pen.java.
Referenced by model.Pen.getStroke().
Strokes model.Pen.myStrokeType private
Definition at line 27 of file Pen.java.
Referenced by model.Pen.getStrokeType().
boolean model.Pen.penWriting = true private
Definition at line 24 of file Pen.java.
Referenced by model.Pen.isPenWriting().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/model/Pen.java