sLogo: parser.CustomCommand Class Reference
parser.CustomCommand Class Reference
Public Member Functions
CustomCommand (String name, int argcount)
void addParserInfo (ListNode params, ListNode commands) throws InvalidArgumentsException
String getName ()
ListNode getCommands ()
int getNumArgs ()
List< VariableNode > getArgs ()
boolean isCreated ()
Private Attributes
String myName
int myArgCount
List< VariableNode > myArgs
ListNode myCommands
Static Private Attributes
static final String LIST_ARGS_VAR
Detailed Description
Contains all the Information of a custom command.
Author
Jonathan Schmidt
Definition at line 17 of file CustomCommand.java.
Constructor & Destructor Documentation
parser.CustomCommand.CustomCommand (String name, int argcount)
Create a Custom Command with the specified name and number of arguments.
Parameters
name The name of the command
argcount The number of arguments
Definition at line 35 of file CustomCommand.java.
Member Function Documentation
void parser.CustomCommand.addParserInfo (ListNode params, ListNode commands) throws InvalidArgumentsException
Adds the information from the parser to this method.
Parameters
params ListNode of parameters
commands ListNode of commands to run that define this command
Exceptions
InvalidArgumentsException
Definition at line 47 of file CustomCommand.java.
Referenced by parser.commands.other.To.evaluate().
List<VariableNode> parser.CustomCommand.getArgs ()
Returns
the Arguments of this command
Definition at line 83 of file CustomCommand.java.
References parser.CustomCommand.myArgs.
Referenced by parser.nodes.CommandNode.evaluate().
ListNode parser.CustomCommand.getCommands ()
Returns
the commands to run for this command
Definition at line 68 of file CustomCommand.java.
References parser.CustomCommand.myCommands.
Referenced by parser.nodes.CommandNode.evaluate().
String parser.CustomCommand.getName ()
Returns
the name of the custom command
Definition at line 61 of file CustomCommand.java.
References parser.CustomCommand.myName.
Referenced by controller.Workspace.addCommand().
int parser.CustomCommand.getNumArgs ()
Returns
The number of arguments
Definition at line 76 of file CustomCommand.java.
References parser.CustomCommand.myArgCount.
Referenced by parser.nodes.CommandNode.CommandNode(), and parser.nodes.CommandNode.evaluate().
boolean parser.CustomCommand.isCreated ()
Returns true if this command has actually been created. As in all the properties have been added to it.
Returns
Definition at line 93 of file CustomCommand.java.
Member Data Documentation
final String parser.CustomCommand.LIST_ARGS_VAR static private
Initial value:
=
            "The list of arguments does not exclusively contain variables."
Definition at line 19 of file CustomCommand.java.
int parser.CustomCommand.myArgCount private
Definition at line 24 of file CustomCommand.java.
Referenced by parser.CustomCommand.getNumArgs().
List<VariableNode> parser.CustomCommand.myArgs private
Definition at line 25 of file CustomCommand.java.
Referenced by parser.CustomCommand.getArgs().
ListNode parser.CustomCommand.myCommands private
Definition at line 26 of file CustomCommand.java.
Referenced by parser.CustomCommand.getCommands().
String parser.CustomCommand.myName private
Definition at line 22 of file CustomCommand.java.
Referenced by parser.CustomCommand.getName().
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/CustomCommand.java