sLogo: parser.Parser Class Reference
parser.Parser Class Reference
Public Member Functions
Parser ()
List< SyntaxNode > parseCommand (String command) throws InvalidSemanticsException
List< SyntaxNode > parseCommand (Scanner s) throws InvalidSemanticsException
Private Attributes
SemanticsChecker mySemantics
Detailed Description
The main class for parsing commands into usable things. Uses the Lex Checker and Semantics Checker to build abstract syntax trees.
Author
Jonathan Schmidt
Definition at line 16 of file Parser.java.
Constructor & Destructor Documentation
parser.Parser.Parser ()
Creates a new instance of the parser.
Definition at line 23 of file Parser.java.
Member Function Documentation
List<SyntaxNode> parser.Parser.parseCommand (String command) throws InvalidSemanticsException
Parses a string command and turns it into a list of trees. Each SyntaxNode is the head of a tree that represents a command.
Parameters
command The string input that the parser parses.
Returns
a list of roots of each tree.
Exceptions
InvalidSemanticsException Throws when there is something invalid in the provided commands
Definition at line 36 of file Parser.java.
References parser.SemanticsChecker.evaluateExpression(), and parser.LexChecker.splitTokens().
Referenced by parser.Main.checkFile(), parser.Parser.parseCommand(), controller.Controller.processCommand(), controller.Controller.processFile(), parser.tests.BooleanTester.testAnd(), parser.tests.MathTester.testDifference(), parser.tests.BooleanTester.testEqual(), parser.tests.BooleanTester.testGreaterThan(), parser.tests.BooleanTester.testLessThan(), parser.tests.MathTester.testMinus(), parser.tests.BooleanTester.testNot(), parser.tests.BooleanTester.testNotEqual(), parser.tests.BooleanTester.testOr(), parser.tests.MathTester.testProduct(), parser.tests.MathTester.testQuotient(), parser.tests.MathTester.testRandom(), parser.tests.MathTester.testRemainder(), and parser.tests.MathTester.testSum().
List<SyntaxNode> parser.Parser.parseCommand (Scanner s) throws InvalidSemanticsException
Parses a command from a Scanner input.
Parameters
s The scanner that contains the commands.
Returns
a list of roots of each tree
Exceptions
InvalidSemanticsException Throws when there is something invalid in the provided commands
Definition at line 51 of file Parser.java.
References parser.Parser.parseCommand().
Member Data Documentation
SemanticsChecker parser.Parser.mySemantics private
Definition at line 18 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/Parser.java