sLogo: parser.nodes.BinaryNode Class Reference
parser.nodes.BinaryNode Class Reference abstract
Public Member Functions
BinaryNode (SyntaxNode left, SyntaxNode right)
BinaryNode (Deque< SyntaxNode > queue)
SyntaxNode getLeft ()
SyntaxNode getRight ()
Public Member Functions inherited from parser.nodes.ParameterNode
int getParameterCount ()
Public Member Functions inherited from parser.nodes.SyntaxNode
abstract int evaluate (IParserProvider w) throws InvalidArgumentsException
Static Private Attributes
static final int LEFT_PARAM = 0
static final int RIGHT_PARAM = 1
Additional Inherited Members
Protected Member Functions inherited from parser.nodes.ParameterNode
void addParameter (int index, SyntaxNode node)
SyntaxNode getParameter (int index)
Detailed Description
This is the base class for a command that has two arguments.
Author
Jonathan Schmidt
Definition at line 12 of file BinaryNode.java.
Constructor & Destructor Documentation
parser.nodes.BinaryNode.BinaryNode (SyntaxNode left, SyntaxNode right)
Creates the BinaryNode with two Syntax Nodes as parameters
Parameters
left Left Argument
right Right Argument
Definition at line 23 of file BinaryNode.java.
References parser.nodes.ParameterNode.addParameter().
parser.nodes.BinaryNode.BinaryNode (Deque< SyntaxNode > queue)
Takes in a Deque and pulls two elements off it.
Parameters
queue The queue that contains the parameters.
Definition at line 33 of file BinaryNode.java.
Member Function Documentation
SyntaxNode parser.nodes.BinaryNode.getLeft ()
Returns the left argument.
Returns
Definition at line 42 of file BinaryNode.java.
References parser.nodes.ParameterNode.getParameter().
Referenced by parser.commands.other.To.checkSyntax(), parser.commands.other.DoTimes.checkSyntax(), parser.commands.workspace.Ask.checkSyntax(), parser.commands.workspace.AskWith.checkSyntax(), parser.commands.other.For.checkSyntax(), parser.commands.turtle.commands.Towards.evaluate(), parser.commands.math.Product.evaluate(), parser.commands.math.Sum.evaluate(), parser.commands.turtle.commands.SetPosition.evaluate(), parser.commands.math.Difference.evaluate(), parser.commands.bool.LessThan.evaluate(), parser.commands.other.IfElse.evaluate(), parser.commands.bool.And.evaluate(), parser.commands.bool.Equal.evaluate(), parser.commands.other.If.evaluate(), parser.commands.bool.Or.evaluate(), parser.commands.bool.NotEqual.evaluate(), parser.commands.bool.GreaterThan.evaluate(), parser.commands.math.Remainder.evaluate(), parser.commands.other.Repeat.evaluate(), parser.commands.math.Quotient.evaluate(), parser.commands.other.Make.evaluate(), parser.commands.other.To.evaluate(), parser.commands.other.DoTimes.evaluate(), parser.commands.workspace.Ask.evaluate(), parser.commands.workspace.AskWith.evaluate(), and parser.commands.other.For.evaluate().
SyntaxNode parser.nodes.BinaryNode.getRight ()
Returns the right argument.
Returns
Definition at line 51 of file BinaryNode.java.
References parser.nodes.ParameterNode.getParameter().
Referenced by parser.commands.other.To.checkSyntax(), parser.commands.other.DoTimes.checkSyntax(), parser.commands.workspace.Ask.checkSyntax(), parser.commands.workspace.AskWith.checkSyntax(), parser.commands.other.For.checkSyntax(), parser.commands.turtle.commands.Towards.evaluate(), parser.commands.math.Product.evaluate(), parser.commands.math.Sum.evaluate(), parser.commands.turtle.commands.SetPosition.evaluate(), parser.commands.math.Difference.evaluate(), parser.commands.bool.LessThan.evaluate(), parser.commands.other.IfElse.evaluate(), parser.commands.bool.And.evaluate(), parser.commands.bool.Equal.evaluate(), parser.commands.other.If.evaluate(), parser.commands.bool.Or.evaluate(), parser.commands.bool.NotEqual.evaluate(), parser.commands.bool.GreaterThan.evaluate(), parser.commands.math.Remainder.evaluate(), parser.commands.other.Repeat.evaluate(), parser.commands.math.Quotient.evaluate(), parser.commands.other.Make.evaluate(), parser.commands.other.To.evaluate(), parser.commands.other.DoTimes.evaluate(), parser.commands.workspace.Ask.evaluate(), parser.commands.workspace.AskWith.evaluate(), and parser.commands.other.For.evaluate().
Member Data Documentation
final int parser.nodes.BinaryNode.LEFT_PARAM = 0 static private
Definition at line 14 of file BinaryNode.java.
final int parser.nodes.BinaryNode.RIGHT_PARAM = 1 static private
Definition at line 15 of file BinaryNode.java.
The documentation for this class was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/parser/Nodes/BinaryNode.java