sLogo: view.components.Error Enum Reference
view.components.Error Enum Reference
Public Member Functions
Error (String error)
String getMessage ()
Public Attributes
INVALID_FILE =(ErrorBox.ERROR_RESOURCE.getString("InvalidFile"))
INVALID_IMAGE =(ErrorBox.ERROR_RESOURCE.getString("InvalidImage"))
NO_WORKSPACE =(ErrorBox.ERROR_RESOURCE.getString("NoWorkspaceYet"))
Private Attributes
final String errorMessage
Detailed Description
Author
Henrique Moraes
Definition at line 8 of file Error.java.
Constructor & Destructor Documentation
view.components.Error.Error (String error)
Definition at line 15 of file Error.java.
Member Function Documentation
String view.components.Error.getMessage ()
Definition at line 19 of file Error.java.
Referenced by view.components.ErrorBox.showError().
Member Data Documentation
final String view.components.Error.errorMessage private
Definition at line 13 of file Error.java.
view.components.Error.INVALID_FILE =(ErrorBox.ERROR_RESOURCE.getString("InvalidFile"))
Definition at line 9 of file Error.java.
view.components.Error.INVALID_IMAGE =(ErrorBox.ERROR_RESOURCE.getString("InvalidImage"))
Definition at line 10 of file Error.java.
Referenced by model.TurtleManager.addTurtleImage(), model.TurtleManager.setImage(), and model.TurtleManager.setImageRelative().
view.components.Error.NO_WORKSPACE =(ErrorBox.ERROR_RESOURCE.getString("NoWorkspaceYet"))
Definition at line 11 of file Error.java.
The documentation for this enum was generated from the following file:
/tmp/Tadimsky/sLogo/repository/src/view/components/Error.java